# Related Artists Spotify Playlist Generator aka RASPG
https://r.isba.co/spotify-playlist-generator-template


## Workflow

![Spotify Playlist Creation Workflow](https://drive.usercontent.google.com/download?id=1ittLJGF67bKfz8o8ohvbBkCeTjQfEShD)

## Account Setup
1. Log in to https://spotify.com
2. Go to https://developer.spotify.com/dashboard/ (log in if needed) to set up a Spotify Developer account

### Explore API endpoints in the Spotify Web API Console  
https://developer.spotify.com/documentation/web-api

## Import required packages

In [1]:
from urllib.parse import urlencode
import requests
import pandas as pd
import json

## How to let your app safely access Spotify on behalf of a user
Your app is your Jupyter Notebook ... for now.  
The user is you but could be somebody else.

## Retrieve the Client ID and Client Secret for your application
- Go to https://developer.spotify.com/dashboard/applications
- Log in and create a new application
- Once the is application created, you will see your Client ID and Client Secret under the Settings button

![Spotify Authorization Code Flow](https://developer.spotify.com/images/documentation/web-api/auth-code-flow.png)

## Set your client_id and client_secret

In [2]:
client_id = '951782aa84c243559e2e7640422391d3'
client_secret = '3d98ea786fbf4f4ea52a2c531ad8969d'

## Get the user authorization code
https://developer.spotify.com/documentation/web-api/concepts/authorization

In [3]:
auth_params= {
    'client_id': client_id,
    'response_type': 'code',
    'redirect_uri': 'https://localhost',
    'scope': 'playlist-modify-public playlist-modify-private'
}
print(f'auth_params: {auth_params}')
auth_params_encoded = urlencode(auth_params)
print(f'auth_params_encoded: {auth_params_encoded}')

auth_url = f'https://accounts.spotify.com/authorize?{auth_params_encoded}'
print(f'Go to this URL to authorize: {auth_url}')

auth_code = input('Enter the authorization code:')

auth_params: {'client_id': '951782aa84c243559e2e7640422391d3', 'response_type': 'code', 'redirect_uri': 'https://localhost', 'scope': 'playlist-modify-public playlist-modify-private'}
auth_params_encoded: client_id=951782aa84c243559e2e7640422391d3&response_type=code&redirect_uri=https%3A%2F%2Flocalhost&scope=playlist-modify-public+playlist-modify-private
Go to this URL to authorize: https://accounts.spotify.com/authorize?client_id=951782aa84c243559e2e7640422391d3&response_type=code&redirect_uri=https%3A%2F%2Flocalhost&scope=playlist-modify-public+playlist-modify-private

Enter the authorization code: AQCgXP56_vcmv9K-qHZeKPP8vPWMUVU-xaoHc0KT8XNhoTiG6CpF-2IWU85WTUfYSeifTdOPPqOO5AdJD0XikyMlFu-ygTQQzexyO9zThB5hq8fErgeAjH-rgyTqilzDI7auxNS3-SYQfqtegNF4YeMZ7NVXxAV4erLBVJ2XssS_wj2x790zJXzH9i2J_hpgvJXJZrlDtEdNCIQhyaWSleorTtiHNg

Go to the generated URL to authorize.

Copy the authorization code (the value after http://localhost/?code=).

In [4]:
auth_code

'AQCgXP56_vcmv9K-qHZeKPP8vPWMUVU-xaoHc0KT8XNhoTiG6CpF-2IWU85WTUfYSeifTdOPPqOO5AdJD0XikyMlFu-ygTQQzexyO9zThB5hq8fErgeAjH-rgyTqilzDI7auxNS3-SYQfqtegNF4YeMZ7NVXxAV4erLBVJ2XssS_wj2x790zJXzH9i2J_hpgvJXJZrlDtEdNCIQhyaWSleorTtiHNg'

## Exchange the authorization code for an access token
https://developer.spotify.com/documentation/web-api/concepts/access-token

In [5]:
token_url = 'https://accounts.spotify.com/api/token'

data = {
    'grant_type': 'authorization_code',
    'code': auth_code,
    'redirect_uri': 'https://localhost',
    'client_id': client_id,
    'client_secret': client_secret
}

response = requests.post(token_url, data=data)
token_response = response.json()

In [6]:
token_response

{'access_token': 'BQAMjC-_qoGjHY-Jow8d1_KnpZ-aQdaBS0YJzWMjSfBnDvb8bMgHKd6A7tdxf3JuibTYHlhV8FzMzMx30DaSA6eM9g7rwKeRiBc4xl4txLOV9J16EzGIvHRoQ6ILtCepDAakdPKxk4Lyjp-MT3Qhk8Lhbk-s_xd7ckOvcFZZa85zMHtqK7m9H6WQK54CAnZc49vA2rJD-dY0j2conRUSVtOT6jn3irMkAAKSjcYB8wqU8cyXGWDbMw',
 'token_type': 'Bearer',
 'expires_in': 3600,
 'refresh_token': 'AQDCkIOv6VG_pEpoMbyoHbO63VDg1jqYuUHNypgkIMxJ4lqPGKkApt5-xhzPe2juOsZJNG8KPUWXO75mkTljEJGYVkbGf6tWgG-gYaoGfjrQ6Vr_D9LF9O9QgFtg8FOfNaM',
 'scope': 'playlist-modify-private playlist-modify-public'}

In [7]:
access_token = token_response['access_token']
access_token

'BQAMjC-_qoGjHY-Jow8d1_KnpZ-aQdaBS0YJzWMjSfBnDvb8bMgHKd6A7tdxf3JuibTYHlhV8FzMzMx30DaSA6eM9g7rwKeRiBc4xl4txLOV9J16EzGIvHRoQ6ILtCepDAakdPKxk4Lyjp-MT3Qhk8Lhbk-s_xd7ckOvcFZZa85zMHtqK7m9H6WQK54CAnZc49vA2rJD-dY0j2conRUSVtOT6jn3irMkAAKSjcYB8wqU8cyXGWDbMw'

### With the access token, you can now access the Spotify API ... until the token expires or is refreshed.

## Set the Authorization header you will pass to every API request to authenticate your app

In [8]:
auth_headers = {
    'Authorization': f'Bearer {access_token}'
}

## Search for an artist and get their artist ID
https://developer.spotify.com/documentation/web-api/reference/search

In [9]:
# Set the artist name to search for
artist_name = 'Porter Robinson'

search_url = 'https://api.spotify.com/v1/search'

params = {
    'q': artist_name,
    'type': 'artist',
    'limit': 1
}

response = requests.get(search_url, headers=auth_headers, params=params)
search_response = response.json()

In [10]:
search_response

{'artists': {'href': 'https://api.spotify.com/v1/search?query=Porter+Robinson&type=artist&offset=0&limit=1',
  'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'followers': {'href': None, 'total': 1165781},
    'genres': ['complextro',
     'edm',
     'electro house',
     'pop dance',
     'progressive electro house'],
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab6761610000e5eb1ac12dcb2cc4fc7c740c5e0c',
      'width': 640},
     {'height': 320,
      'url': 'https://i.scdn.co/image/ab676161000051741ac12dcb2cc4fc7c740c5e0c',
      'width': 320},
     {'height': 160,
      'url': 'https://i.scdn.co/image/ab6761610000f1781ac12dcb2cc4fc7c740c5e0c',
      'width': 160}],
    'name': 'Porter Robinson',
    'popularity': 65,
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'limit': 1,
  'next': 'https://api.spotify.com/v1/search?query=Porter+Robinson&type=artist&offset=1&limit=1',
  'offset': 0,
  'previous': None,
  'total': 801}}

In [11]:
search_response['artists']

{'href': 'https://api.spotify.com/v1/search?query=Porter+Robinson&type=artist&offset=0&limit=1',
 'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
   'followers': {'href': None, 'total': 1165781},
   'genres': ['complextro',
    'edm',
    'electro house',
    'pop dance',
    'progressive electro house'],
   'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
   'id': '3dz0NnIZhtKKeXZxLOxCam',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab6761610000e5eb1ac12dcb2cc4fc7c740c5e0c',
     'width': 640},
    {'height': 320,
     'url': 'https://i.scdn.co/image/ab676161000051741ac12dcb2cc4fc7c740c5e0c',
     'width': 320},
    {'height': 160,
     'url': 'https://i.scdn.co/image/ab6761610000f1781ac12dcb2cc4fc7c740c5e0c',
     'width': 160}],
   'name': 'Porter Robinson',
   'popularity': 65,
   'type': 'artist',
   'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
 'limit': 1,
 'next': 'https://api.spotify.com/v1/search?query=Porter+Robinson&type=artist&offset=1&limit=1',
 'offset': 0,
 'previous': None,
 'total': 801}

In [12]:
artist_id = search_response['artists']['items'][0]['id']
artist_id

'3dz0NnIZhtKKeXZxLOxCam'

## Get the artist's top tracks
https://developer.spotify.com/documentation/web-api/reference/get-an-artists-top-tracks

In [13]:
top_tracks_url = f'https://api.spotify.com/v1/artists/{artist_id}/top-tracks'

params = {
    'market': 'US'
}

response = requests.get(top_tracks_url, headers=auth_headers, params=params)
top_tracks_response = response.json()

In [14]:
top_tracks_response

{'tracks': [{'album': {'album_type': 'single',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc'},
      'href': 'https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc',
      'id': '4pb4rqWSoGUgxm63xmJ8xc',
      'name': 'Madeon',
      'type': 'artist',
      'uri': 'spotify:artist:4pb4rqWSoGUgxm63xmJ8xc'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2vVfxcvBQAGnEKM3zM0zxw'},
    'href': 'https://api.spotify.com/v1/albums/2vVfxcvBQAGnEKM3zM0zxw',
    'id': '2vVfxcvBQAGnEKM3zM0zxw',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731a5eb771120e2ee3f6a44ed7',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e021a5eb771120e2ee3f6a44ed7',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d000048511a5eb771120e2ee3f6a44ed7',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'Shelter',
    'release_date': '2016-08-12',
    'release_date_precision': 'day',
    'total_tracks': 1,
    'type': 'album',
    'uri': 'spotify:album:2vVfxcvBQAGnEKM3zM0zxw'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc'},
     'href': 'https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc',
     'id': '4pb4rqWSoGUgxm63xmJ8xc',
     'name': 'Madeon',
     'type': 'artist',
     'uri': 'spotify:artist:4pb4rqWSoGUgxm63xmJ8xc'}],
   'disc_number': 1,
   'duration_ms': 218964,
   'explicit': False,
   'external_ids': {'isrc': 'QMUY41600040'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/2ewEh7LuvToYyGHq7yT8N1'},
   'href': 'https://api.spotify.com/v1/tracks/2ewEh7LuvToYyGHq7yT8N1',
   'id': '2ewEh7LuvToYyGHq7yT8N1',
   'is_local': False,
   'is_playable': True,
   'name': 'Shelter',
   'popularity': 61,
   'preview_url': 'https://p.scdn.co/mp3-preview/50c7dbdb7d3e86153d7cc2b2ba28fad29fa0ce6e?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 1,
   'type': 'track',
   'uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
    'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
    'id': '2iS4pBIiQf4sCTJLZ5n8dy',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'SMILE! :D',
    'release_date': '2024-07-26',
    'release_date_precision': 'day',
    'total_tracks': 10,
    'type': 'album',
    'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 237567,
   'explicit': False,
   'external_ids': {'isrc': 'USQE92400031'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/5iyuwVaMliMdloOzSBxohv'},
   'href': 'https://api.spotify.com/v1/tracks/5iyuwVaMliMdloOzSBxohv',
   'id': '5iyuwVaMliMdloOzSBxohv',
   'is_local': False,
   'is_playable': True,
   'name': 'Cheerleader',
   'popularity': 58,
   'preview_url': 'https://p.scdn.co/mp3-preview/787d4faa1c0b99287d06a97cdef736419de42c57?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 2,
   'type': 'track',
   'uri': 'spotify:track:5iyuwVaMliMdloOzSBxohv'},
  {'album': {'album_type': 'single',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/47mIJdHORyRerp4os813jD'},
      'href': 'https://api.spotify.com/v1/artists/47mIJdHORyRerp4os813jD',
      'id': '47mIJdHORyRerp4os813jD',
      'name': 'League of Legends',
      'type': 'artist',
      'uri': 'spotify:artist:47mIJdHORyRerp4os813jD'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/0j4PaZDmzAJ4PlS89zcHbW'},
    'href': 'https://api.spotify.com/v1/albums/0j4PaZDmzAJ4PlS89zcHbW',
    'id': '0j4PaZDmzAJ4PlS89zcHbW',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2732b1a62237771427afb899387',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e022b1a62237771427afb899387',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d000048512b1a62237771427afb899387',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'Everything Goes On',
    'release_date': '2022-07-14',
    'release_date_precision': 'day',
    'total_tracks': 1,
    'type': 'album',
    'uri': 'spotify:album:0j4PaZDmzAJ4PlS89zcHbW'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/47mIJdHORyRerp4os813jD'},
     'href': 'https://api.spotify.com/v1/artists/47mIJdHORyRerp4os813jD',
     'id': '47mIJdHORyRerp4os813jD',
     'name': 'League of Legends',
     'type': 'artist',
     'uri': 'spotify:artist:47mIJdHORyRerp4os813jD'}],
   'disc_number': 1,
   'duration_ms': 202821,
   'explicit': False,
   'external_ids': {'isrc': 'QZH6S1900628'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/3WBRfkOozHEsG0hbrBzwlm'},
   'href': 'https://api.spotify.com/v1/tracks/3WBRfkOozHEsG0hbrBzwlm',
   'id': '3WBRfkOozHEsG0hbrBzwlm',
   'is_local': False,
   'is_playable': True,
   'name': 'Everything Goes On',
   'popularity': 60,
   'preview_url': 'https://p.scdn.co/mp3-preview/2dfc39ada0221d0948aa6230558121f4b52eb197?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 1,
   'type': 'track',
   'uri': 'spotify:track:3WBRfkOozHEsG0hbrBzwlm'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD'},
    'href': 'https://api.spotify.com/v1/albums/7AJPV0L05IyIBid97AvwVD',
    'id': '7AJPV0L05IyIBid97AvwVD',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731f675e7b8bae408653346dd9',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e021f675e7b8bae408653346dd9',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d000048511f675e7b8bae408653346dd9',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'Worlds',
    'release_date': '2014-08-12',
    'release_date_precision': 'day',
    'total_tracks': 12,
    'type': 'album',
    'uri': 'spotify:album:7AJPV0L05IyIBid97AvwVD'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 328506,
   'explicit': False,
   'external_ids': {'isrc': 'USUG11400557'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/786ymAh5BmHoIpvjyrvjXk'},
   'href': 'https://api.spotify.com/v1/tracks/786ymAh5BmHoIpvjyrvjXk',
   'id': '786ymAh5BmHoIpvjyrvjXk',
   'is_local': False,
   'is_playable': True,
   'name': 'Goodbye To A World',
   'popularity': 58,
   'preview_url': 'https://p.scdn.co/mp3-preview/db5e5ded18f02c743a78c0369a57c5e1ff79baae?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 12,
   'type': 'track',
   'uri': 'spotify:track:786ymAh5BmHoIpvjyrvjXk'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
    'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
    'id': '2iS4pBIiQf4sCTJLZ5n8dy',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'SMILE! :D',
    'release_date': '2024-07-26',
    'release_date_precision': 'day',
    'total_tracks': 10,
    'type': 'album',
    'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 168277,
   'explicit': False,
   'external_ids': {'isrc': 'USQE92400082'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/6yfY7OdAz4VEOjPUOP3yzN'},
   'href': 'https://api.spotify.com/v1/tracks/6yfY7OdAz4VEOjPUOP3yzN',
   'id': '6yfY7OdAz4VEOjPUOP3yzN',
   'is_local': False,
   'is_playable': True,
   'name': 'Knock Yourself Out XD',
   'popularity': 56,
   'preview_url': 'https://p.scdn.co/mp3-preview/b309960950d891387fb2acd4f4d7604e187879a0?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 1,
   'type': 'track',
   'uri': 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
    'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
    'id': '2iS4pBIiQf4sCTJLZ5n8dy',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'SMILE! :D',
    'release_date': '2024-07-26',
    'release_date_precision': 'day',
    'total_tracks': 10,
    'type': 'album',
    'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 199668,
   'explicit': False,
   'external_ids': {'isrc': 'USQE92400089'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/3eE6IderHf7lnqOorqiNVK'},
   'href': 'https://api.spotify.com/v1/tracks/3eE6IderHf7lnqOorqiNVK',
   'id': '3eE6IderHf7lnqOorqiNVK',
   'is_local': False,
   'is_playable': True,
   'name': 'Is There Really No Happiness?',
   'popularity': 57,
   'preview_url': 'https://p.scdn.co/mp3-preview/a95a22001e0e048524e8dfec65478d029cdd3396?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 9,
   'type': 'track',
   'uri': 'spotify:track:3eE6IderHf7lnqOorqiNVK'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
    'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
    'id': '2iS4pBIiQf4sCTJLZ5n8dy',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'SMILE! :D',
    'release_date': '2024-07-26',
    'release_date_precision': 'day',
    'total_tracks': 10,
    'type': 'album',
    'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 388800,
   'explicit': True,
   'external_ids': {'isrc': 'USQE92400083'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/3RdUgst4llmyJkVtNaqHGv'},
   'href': 'https://api.spotify.com/v1/tracks/3RdUgst4llmyJkVtNaqHGv',
   'id': '3RdUgst4llmyJkVtNaqHGv',
   'is_local': False,
   'is_playable': True,
   'name': 'Russian Roulette',
   'popularity': 55,
   'preview_url': 'https://p.scdn.co/mp3-preview/de199e6c7a09d9df55c4fb19a3b9f1c423a79fb8?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 3,
   'type': 'track',
   'uri': 'spotify:track:3RdUgst4llmyJkVtNaqHGv'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD'},
    'href': 'https://api.spotify.com/v1/albums/7AJPV0L05IyIBid97AvwVD',
    'id': '7AJPV0L05IyIBid97AvwVD',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731f675e7b8bae408653346dd9',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e021f675e7b8bae408653346dd9',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d000048511f675e7b8bae408653346dd9',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'Worlds',
    'release_date': '2014-08-12',
    'release_date_precision': 'day',
    'total_tracks': 12,
    'type': 'album',
    'uri': 'spotify:album:7AJPV0L05IyIBid97AvwVD'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 350690,
   'explicit': False,
   'external_ids': {'isrc': 'USUG11400374'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/1JY6B9ILvmRla2IKKRZvnH'},
   'href': 'https://api.spotify.com/v1/tracks/1JY6B9ILvmRla2IKKRZvnH',
   'id': '1JY6B9ILvmRla2IKKRZvnH',
   'is_local': False,
   'is_playable': True,
   'name': 'Sad Machine',
   'popularity': 55,
   'preview_url': 'https://p.scdn.co/mp3-preview/cdc2417a6df9dd1e30666bb6fc9d1f8d9c15c0a9?cid=951782aa84c243559e2e7640422391d3',
   'track_number': 2,
   'type': 'track',
   'uri': 'spotify:track:1JY6B9ILvmRla2IKKRZvnH'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
      'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
      'id': '3dz0NnIZhtKKeXZxLOxCam',
      'name': 'Porter Robinson',
      'type': 'artist',
      'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/4Hjqdhj5rh816i1dfcUEaM'},
    'href': 'https://api.spotify.com/v1/albums/4Hjqdhj5rh816i1dfcUEaM',
    'id': '4Hjqdhj5rh816i1dfcUEaM',
    'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2737d6ac8b4a84ad4b342050d87',
      'width': 640,
      'height': 640},
     {'url': 'https://i.scdn.co/image/ab67616d00001e027d6ac8b4a84ad4b342050d87',
      'width': 300,
      'height': 300},
     {'url': 'https://i.scdn.co/image/ab67616d000048517d6ac8b4a84ad4b342050d87',
      'width': 64,
      'height': 64}],
    'is_playable': True,
    'name': 'Nurture',
    'release_date': '2021-04-23',
    'release_date_precision': 'day',
    'total_tracks': 14,
    'type': 'album',
    'uri': 'spotify:album:4Hjqdhj5rh816i1dfcUEaM'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'disc_number': 1,
   'duration_ms': 309985,
   'explicit': False,
   'external_ids': {'isrc': 'USQE92000004'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/5lXNcc8QeM9KpAWNHAL0iS'},
   'href': 'https://api.spotify.com/v1/tracks/5lXNcc8QeM9KpAWNHAL0iS',
   'id': '5lXNcc8QeM9KpAWNHAL0iS',

In [15]:
top_tracks = top_tracks_response['tracks']

In [16]:
type(top_tracks)

list

In [17]:
len(top_tracks)

10

## Get the artist's related artists
https://developer.spotify.com/documentation/web-api/reference/get-an-artists-related-artists

In [18]:
related_artists_url = f'https://api.spotify.com/v1/artists/{artist_id}/related-artists'

response = requests.get(related_artists_url, headers=auth_headers)
related_artists_response = response.json()

In [19]:
related_artists = related_artists_response['artists']
related_artists

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc'},
  'followers': {'href': None, 'total': 651631},
  'genres': ['complextro',
   'edm',
   'electro house',
   'electropop',
   'filter house',
   'nantes indie',
   'pop dance'],
  'href': 'https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc',
  'id': '4pb4rqWSoGUgxm63xmJ8xc',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebeb3e154881ba6cc3e4d4980d',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174eb3e154881ba6cc3e4d4980d',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178eb3e154881ba6cc3e4d4980d',
    'height': 160,
    'width': 160}],
  'name': 'Madeon',
  'popularity': 56,
  'type': 'artist',
  'uri': 'spotify:artist:4pb4rqWSoGUgxm63xmJ8xc'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/0jNDKefhfSbLR9sFvcPLHo'},
  'followers': {'href': None, 'total': 696440},
  'genres': ['brostep',
   'edm',
   'electro house',
   'electronic trap',
   'future bass',
   'pop dance'],
  'href': 'https://api.spotify.com/v1/artists/0jNDKefhfSbLR9sFvcPLHo',
  'id': '0jNDKefhfSbLR9sFvcPLHo',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb082c34e225913f6f5ef6f420',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174082c34e225913f6f5ef6f420',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178082c34e225913f6f5ef6f420',
    'height': 160,
    'width': 160}],
  'name': 'San Holo',
  'popularity': 56,
  'type': 'artist',
  'uri': 'spotify:artist:0jNDKefhfSbLR9sFvcPLHo'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/2Hchwjfl1DioXcIwbOJkus'},
  'followers': {'href': None, 'total': 53232},
  'genres': ['future bass'],
  'href': 'https://api.spotify.com/v1/artists/2Hchwjfl1DioXcIwbOJkus',
  'id': '2Hchwjfl1DioXcIwbOJkus',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb07d7a890f5d86a7cb00c55a9',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab6761610000517407d7a890f5d86a7cb00c55a9',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f17807d7a890f5d86a7cb00c55a9',
    'height': 160,
    'width': 160}],
  'name': 'Grant',
  'popularity': 50,
  'type': 'artist',
  'uri': 'spotify:artist:2Hchwjfl1DioXcIwbOJkus'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/6fcTRFpz0yH79qSKfof7lp'},
  'followers': {'href': None, 'total': 502062},
  'genres': ['brostep',
   'complextro',
   'dubstep',
   'edm',
   'electro house',
   'melodic dubstep',
   'pop dance',
   'progressive trance'],
  'href': 'https://api.spotify.com/v1/artists/6fcTRFpz0yH79qSKfof7lp',
  'id': '6fcTRFpz0yH79qSKfof7lp',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebcadf84cce5c74aa27a8c1311',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174cadf84cce5c74aa27a8c1311',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178cadf84cce5c74aa27a8c1311',
    'height': 160,
    'width': 160}],
  'name': 'Seven Lions',
  'popularity': 62,
  'type': 'artist',
  'uri': 'spotify:artist:6fcTRFpz0yH79qSKfof7lp'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lZauDnRoAC3kmaYae2opv'},
  'followers': {'href': None, 'total': 185180},
  'genres': ['canadian electronic', 'melodic dubstep', 'pop edm'],
  'href': 'https://api.spotify.com/v1/artists/7lZauDnRoAC3kmaYae2opv',
  'id': '7lZauDnRoAC3kmaYae2opv',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebf7ef0932483c22930c1990eb',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174f7ef0932483c22930c1990eb',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178f7ef0932483c22930c1990eb',
    'height': 160,
    'width': 160}],
  'name': 'Dabin',
  'popularity': 58,
  'type': 'artist',
  'uri': 'spotify:artist:7lZauDnRoAC3kmaYae2opv'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/1SlTeYo2NYg93bGqlQYkwE'},
  'followers': {'href': None, 'total': 43090},
  'genres': ['brostep'],
  'href': 'https://api.spotify.com/v1/artists/1SlTeYo2NYg93bGqlQYkwE',
  'id': '1SlTeYo2NYg93bGqlQYkwE',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eba2eb8772c7436c49184d4594',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174a2eb8772c7436c49184d4594',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178a2eb8772c7436c49184d4594',
    'height': 160,
    'width': 160}],
  'name': 'Wavedash',
  'popularity': 39,
  'type': 'artist',
  'uri': 'spotify:artist:1SlTeYo2NYg93bGqlQYkwE'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/229NvsczXKwdH0DkPg4uwT'},
  'followers': {'href': None, 'total': 10829},
  'genres': [],
  'href': 'https://api.spotify.com/v1/artists/229NvsczXKwdH0DkPg4uwT',
  'id': '229NvsczXKwdH0DkPg4uwT',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb030b08bad91f6060a0a3243d',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174030b08bad91f6060a0a3243d',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178030b08bad91f6060a0a3243d',
    'height': 160,
    'width': 160}],
  'name': 'McCall',
  'popularity': 40,
  'type': 'artist',
  'uri': 'spotify:artist:229NvsczXKwdH0DkPg4uwT'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/00CYRdkMnA0mwfy1VQPA7X'},
  'followers': {'href': None, 'total': 41188},
  'genres': [],
  'href': 'https://api.spotify.com/v1/artists/00CYRdkMnA0mwfy1VQPA7X',
  'id': '00CYRdkMnA0mwfy1VQPA7X',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb45b209d1c966d98bde06ff19',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab6761610000517445b209d1c966d98bde06ff19',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f17845b209d1c966d98bde06ff19',
    'height': 160,
    'width': 160}],
  'name': 'ellis',
  'popularity': 50,
  'type': 'artist',
  'uri': 'spotify:artist:00CYRdkMnA0mwfy1VQPA7X'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/4LZ4De2MoO3lP6QaNCfvcu'},
  'followers': {'href': None, 'total': 287854},
  'genres': ['melodic dubstep', 'pop edm'],
  'href': 'https://api.spotify.com/v1/artists/4LZ4De2MoO3lP6QaNCfvcu',
  'id': '4LZ4De2MoO3lP6QaNCfvcu',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb4755859fd0d5dfb95ad8e271',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab676161000051744755859fd0d5dfb95ad8e271',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f1784755859fd0d5dfb95ad8e271',
    'height': 160,
    'width': 160}],
  'name': 'Said The Sky',
  'popularity': 57,
  'type': 'artist',
  'uri': 'spotify:artist:4LZ4De2MoO3lP6QaNCfvcu'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/4fv1OFJywZ7DHCz3mVQQ45'},
  'followers': {'href': None, 'total': 113114},
  'genres': ['brostep'],
  'href': 'https://api.spotify.com/v1/artists/4fv1OFJywZ7DHCz3mVQQ45',
  'id': '4fv1OFJywZ7DHCz3mVQQ45',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb7f266447ec4d8307cfc915c9',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab676161000051747f266447ec4d8307cfc915c9',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f1787f266447ec4d8307cfc915c9',
    'height': 160,
    'width': 160}],
  'name': 'Grabbitz',
  'popularity': 60,
  'type': 'artist',
  'uri': 'spotify:artist:4fv1OFJywZ7DHCz3mVQQ45'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/4VqBNQRr0nDN0trNUOn0co'},
  'followers': {'href': None, 'total': 73377},
  'genres': ['complextro', 'future bass', 'gaming edm'],
  'href': 'https://api.spotify.com/v1/artists/4VqBNQRr0nDN0trNUOn0co',
  'id': '4VqBNQRr0nDN0trNUOn0co',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb3ec0f711d80a55fab4d189a9',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab676161000051743ec0f711d80a55fab4d189a9',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f1783ec0f711d80a55fab4d189a9',
    'height': 160,
    'width': 160}],
  'name': 'WRLD',
  'popularity': 43,
  'type': 'artist',
  'uri': 'spotify:artist:4VqBNQRr0nDN0trNUOn0co'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/6qEfyIMkz6rkRRhmuBTFWI'},
  'followers': {'href': None, 'total': 3506},
  'genres': [],
  'href': 'https://api.spotify.com/v1/artists/6qEfyIMkz6rkRRhmuBTFWI',
  'id': '6qEfyIMkz6rkRRhmuBTFWI',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebbd286fdf3a0fb23eee7bca46',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174bd286fdf3a0fb23eee7bca46',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178bd286fdf3a0fb23eee7bca46',
    'height': 160,
    'width': 160}],
  'name': 'meesh',
  'popularity': 34,
  'type': 'artist',
  'uri': 'spotify:artist:6qEfyIMkz6rkRRhmuBTFWI'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/0F52YLV7uWqaJfMMDgG737'},
  'followers': {'href': None, 'total': 116867},
  'genres': ['electro house', 'future bass'],
  'href': 'https://api.spotify.com/v1/artists/0F52YLV7uWqaJfMMDgG737',
  'id': '0F52YLV7uWqaJfMMDgG737',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebd8b3a3a7c3fe3e6cfd835e46',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174d8b3a3a7c3fe3e6cfd835e46',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178d8b3a3a7c3fe3e6cfd835e46',
    'height': 160,
    'width': 160}],
  'name': 'Virtual Self',
  'popularity': 41,
  'type': 'artist',
  'uri': 'spotify:artist:0F52YLV7uWqaJfMMDgG737'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/1BAdSa5cdtCNLbvT7gWmtJ'},
  'followers': {'href': None, 'total': 56848},
  'genres': ['canadian electronic', 'future bass', 'pop edm'],
  'href': 'https://api.spotify.com/v1/artists/1BAdSa5cdtCNLbvT7gWmtJ',
  'id': '1BAdSa5cdtCNLbvT7gWmtJ',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebeb2d069d8b4887fc2a99174a',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174eb2d069d8b4887fc2a99174a',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178eb2d069d8b4887fc2a99174a',
    'height': 160,
    'width': 160}],
  'name': 'Conro',
  'popularity': 48,
  'type': 'artist',
  'uri': 'spotify:artist:1BAdSa5cdtCNLbvT7gWmtJ'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/45eNHdiiabvmbp4erw26rg'},
  'followers': {'href': None, 'total': 1538144},
  'genres': ['edm', 'melodic dubstep', 'pop dance'],
  'href': 'https://api.spotify.com/v1/artists/45eNHdiiabvmbp4erw26rg',
  'id': '45eNHdiiabvmbp4erw26rg',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb81a0ab3a9a4326929a01b0f1',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab6761610000517481a0ab3a9a4326929a01b0f1',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f17881a0ab3a9a4326929a01b0f1',
    'height': 160,
    'width': 160}],
  'name': 'ILLENIUM',
  'popularity': 72,
  'type': 'artist',
  'uri': 'spotify:artist:45eNHdiiabvmbp4erw26rg'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/3RTklnRcfHgkQJwFpgOq3t'},
  'followers': {'href': None, 'total': 69043},
  'genres': ['pop edm'],
  'href': 'https://api.spotify.com/v1/artists/3RTklnRcfHgkQJwFpgOq3t',
  'id': '3RTklnRcfHgkQJwFpgOq3t',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb158ef6d1ac707e415386cb16',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174158ef6d1ac707e415386cb16',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178158ef6d1ac707e415386cb16',
    'height': 160,
    'width': 160}],
  'name': 'Nevve',
  'popularity': 55,
  'type': 'artist',
  'uri': 'spotify:artist:3RTklnRcfHgkQJwFpgOq3t'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/16yUpGkBRgc2eDMd3bB3Uw'},
  'followers': {'href': None, 'total': 154125},
  'genres': ['chillstep',
   'complextro',
   'filthstep',
   'melodic dubstep',
   'pop edm'],
  'href': 'https://api.spotify.com/v1/artists/16yUpGkBRgc2eDMd3bB3Uw',
  'id': '16yUpGkBRgc2eDMd3bB3Uw',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb90fbc988af1793d4522ddd08',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab6761610000517490fbc988af1793d4522ddd08',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f17890fbc988af1793d4522ddd08',
    'height': 160,
    'width': 160}],
  'name': 'MitiS',
  'popularity': 50,
  'type': 'artist',
  'uri': 'spotify:artist:16yUpGkBRgc2eDMd3bB3Uw'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/7HfUJxeVTgrvhk0eWHFzV7'},
  'followers': {'href': None, 'total': 101279},
  'genres': ['hyperpop'],
  'href': 'https://api.spotify.com/v1/artists/7HfUJxeVTgrvhk0eWHFzV7',
  'id': '7HfUJxeVTgrvhk0eWHFzV7',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebde8dfaf8e64fee65ef479e68',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174de8dfaf8e64fee65ef479e68',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178de8dfaf8e64fee65ef479e68',
    'height': 160,
    'width': 160}],
  'name': 'underscores',
  'popularity': 52,
  'type': 'artist',
  'uri': 'spotify:artist:7HfUJxeVTgrvhk0eWHFzV7'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/01qbSocTDAe2DmKayS89A5'},
  'followers': {'href': None, 'total': 78611},
  'genres': ['future bass', 'vapor twitch'],
  'href': 'https://api.spotify.com/v1/artists/01qbSocTDAe2DmKayS89A5',
  'id': '01qbSocTDAe2DmKayS89A5',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb2f829ebd3051573bd390764e',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab676161000051742f829ebd3051573bd390764e',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f1782f829ebd3051573bd390764e',
    'height': 160,
    'width': 160}],
  'name': 'pluko',
  'popularity': 50,
  'type': 'artist',
  'uri': 'spotify:artist:01qbSocTDAe2DmKayS89A5'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/5OeSHuvHTS9qUgAUTt3GIR'},
  'followers': {'href': None, 'total': 14405},
  'genres': ['future bass'],
  'href': 'https://api.spotify.com/v1/artists/5OeSHuvHTS9qUgAUTt3GIR',
  'id': '5OeSHuvHTS9qUgAUTt3GIR',
  'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebcccbbec678f12a90ee769d96',
    'height': 640,
    'width': 640},
   {'url': 'https://i.scdn.co/image/ab67616100005174cccbbec678f12a90ee769d96',
    'height': 320,
    'width': 320},
   {'url': 'https://i.scdn.co/image/ab6761610000f178cccbbec678f12a90ee769d96',
    'height': 160,
    'width': 160}],
  'name': 'acloudyskye',
  'popularity': 35,
  'type': 'artist',
  'uri': 'spotify:artist:5OeSHuvHTS9qUgAUTt3GIR'}]

In [20]:
len(related_artists)

20

## List slicing

```
a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array
```

## Get the top tracks for 3 of the related artists
https://developer.spotify.com/documentation/web-api/reference/get-an-artists-top-tracks

In [21]:
for related_artist in related_artists[0:3]:
    # print(f'related_artist: {related_artist}')
    related_artist_id = related_artist['id']
    print(f'Getting top tracks for related artist: {related_artist_id} - {related_artist['name']}')
    top_tracks_url = f'https://api.spotify.com/v1/artists/{related_artist_id}/top-tracks'

    params = {
        'market': 'US'
    }

    response = requests.get(top_tracks_url, headers=auth_headers, params=params)
    top_tracks_response = response.json()

    related_artist_top_tracks = top_tracks_response['tracks']
    
    top_tracks.extend(related_artist_top_tracks)

Getting top tracks for related artist: 4pb4rqWSoGUgxm63xmJ8xc - Madeon
Getting top tracks for related artist: 0jNDKefhfSbLR9sFvcPLHo - San Holo
Getting top tracks for related artist: 2Hchwjfl1DioXcIwbOJkus - Grant

In [22]:
len(top_tracks)

40

In [23]:
top_tracks

[{'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc'},
     'href': 'https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc',
     'id': '4pb4rqWSoGUgxm63xmJ8xc',
     'name': 'Madeon',
     'type': 'artist',
     'uri': 'spotify:artist:4pb4rqWSoGUgxm63xmJ8xc'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2vVfxcvBQAGnEKM3zM0zxw'},
   'href': 'https://api.spotify.com/v1/albums/2vVfxcvBQAGnEKM3zM0zxw',
   'id': '2vVfxcvBQAGnEKM3zM0zxw',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731a5eb771120e2ee3f6a44ed7',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e021a5eb771120e2ee3f6a44ed7',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d000048511a5eb771120e2ee3f6a44ed7',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'Shelter',
   'release_date': '2016-08-12',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:2vVfxcvBQAGnEKM3zM0zxw'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc'},
    'href': 'https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc',
    'id': '4pb4rqWSoGUgxm63xmJ8xc',
    'name': 'Madeon',
    'type': 'artist',
    'uri': 'spotify:artist:4pb4rqWSoGUgxm63xmJ8xc'}],
  'disc_number': 1,
  'duration_ms': 218964,
  'explicit': False,
  'external_ids': {'isrc': 'QMUY41600040'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/2ewEh7LuvToYyGHq7yT8N1'},
  'href': 'https://api.spotify.com/v1/tracks/2ewEh7LuvToYyGHq7yT8N1',
  'id': '2ewEh7LuvToYyGHq7yT8N1',
  'is_local': False,
  'is_playable': True,
  'name': 'Shelter',
  'popularity': 61,
  'preview_url': 'https://p.scdn.co/mp3-preview/50c7dbdb7d3e86153d7cc2b2ba28fad29fa0ce6e?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
   'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
   'id': '2iS4pBIiQf4sCTJLZ5n8dy',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'SMILE! :D',
   'release_date': '2024-07-26',
   'release_date_precision': 'day',
   'total_tracks': 10,
   'type': 'album',
   'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 237567,
  'explicit': False,
  'external_ids': {'isrc': 'USQE92400031'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/5iyuwVaMliMdloOzSBxohv'},
  'href': 'https://api.spotify.com/v1/tracks/5iyuwVaMliMdloOzSBxohv',
  'id': '5iyuwVaMliMdloOzSBxohv',
  'is_local': False,
  'is_playable': True,
  'name': 'Cheerleader',
  'popularity': 58,
  'preview_url': 'https://p.scdn.co/mp3-preview/787d4faa1c0b99287d06a97cdef736419de42c57?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 2,
  'type': 'track',
  'uri': 'spotify:track:5iyuwVaMliMdloOzSBxohv'},
 {'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/47mIJdHORyRerp4os813jD'},
     'href': 'https://api.spotify.com/v1/artists/47mIJdHORyRerp4os813jD',
     'id': '47mIJdHORyRerp4os813jD',
     'name': 'League of Legends',
     'type': 'artist',
     'uri': 'spotify:artist:47mIJdHORyRerp4os813jD'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/0j4PaZDmzAJ4PlS89zcHbW'},
   'href': 'https://api.spotify.com/v1/albums/0j4PaZDmzAJ4PlS89zcHbW',
   'id': '0j4PaZDmzAJ4PlS89zcHbW',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2732b1a62237771427afb899387',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e022b1a62237771427afb899387',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d000048512b1a62237771427afb899387',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'Everything Goes On',
   'release_date': '2022-07-14',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:0j4PaZDmzAJ4PlS89zcHbW'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/47mIJdHORyRerp4os813jD'},
    'href': 'https://api.spotify.com/v1/artists/47mIJdHORyRerp4os813jD',
    'id': '47mIJdHORyRerp4os813jD',
    'name': 'League of Legends',
    'type': 'artist',
    'uri': 'spotify:artist:47mIJdHORyRerp4os813jD'}],
  'disc_number': 1,
  'duration_ms': 202821,
  'explicit': False,
  'external_ids': {'isrc': 'QZH6S1900628'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/3WBRfkOozHEsG0hbrBzwlm'},
  'href': 'https://api.spotify.com/v1/tracks/3WBRfkOozHEsG0hbrBzwlm',
  'id': '3WBRfkOozHEsG0hbrBzwlm',
  'is_local': False,
  'is_playable': True,
  'name': 'Everything Goes On',
  'popularity': 60,
  'preview_url': 'https://p.scdn.co/mp3-preview/2dfc39ada0221d0948aa6230558121f4b52eb197?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:3WBRfkOozHEsG0hbrBzwlm'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD'},
   'href': 'https://api.spotify.com/v1/albums/7AJPV0L05IyIBid97AvwVD',
   'id': '7AJPV0L05IyIBid97AvwVD',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731f675e7b8bae408653346dd9',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e021f675e7b8bae408653346dd9',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d000048511f675e7b8bae408653346dd9',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'Worlds',
   'release_date': '2014-08-12',
   'release_date_precision': 'day',
   'total_tracks': 12,
   'type': 'album',
   'uri': 'spotify:album:7AJPV0L05IyIBid97AvwVD'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 328506,
  'explicit': False,
  'external_ids': {'isrc': 'USUG11400557'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/786ymAh5BmHoIpvjyrvjXk'},
  'href': 'https://api.spotify.com/v1/tracks/786ymAh5BmHoIpvjyrvjXk',
  'id': '786ymAh5BmHoIpvjyrvjXk',
  'is_local': False,
  'is_playable': True,
  'name': 'Goodbye To A World',
  'popularity': 58,
  'preview_url': 'https://p.scdn.co/mp3-preview/db5e5ded18f02c743a78c0369a57c5e1ff79baae?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 12,
  'type': 'track',
  'uri': 'spotify:track:786ymAh5BmHoIpvjyrvjXk'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
   'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
   'id': '2iS4pBIiQf4sCTJLZ5n8dy',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'SMILE! :D',
   'release_date': '2024-07-26',
   'release_date_precision': 'day',
   'total_tracks': 10,
   'type': 'album',
   'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 168277,
  'explicit': False,
  'external_ids': {'isrc': 'USQE92400082'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/6yfY7OdAz4VEOjPUOP3yzN'},
  'href': 'https://api.spotify.com/v1/tracks/6yfY7OdAz4VEOjPUOP3yzN',
  'id': '6yfY7OdAz4VEOjPUOP3yzN',
  'is_local': False,
  'is_playable': True,
  'name': 'Knock Yourself Out XD',
  'popularity': 56,
  'preview_url': 'https://p.scdn.co/mp3-preview/b309960950d891387fb2acd4f4d7604e187879a0?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
   'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
   'id': '2iS4pBIiQf4sCTJLZ5n8dy',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'SMILE! :D',
   'release_date': '2024-07-26',
   'release_date_precision': 'day',
   'total_tracks': 10,
   'type': 'album',
   'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 199668,
  'explicit': False,
  'external_ids': {'isrc': 'USQE92400089'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/3eE6IderHf7lnqOorqiNVK'},
  'href': 'https://api.spotify.com/v1/tracks/3eE6IderHf7lnqOorqiNVK',
  'id': '3eE6IderHf7lnqOorqiNVK',
  'is_local': False,
  'is_playable': True,
  'name': 'Is There Really No Happiness?',
  'popularity': 57,
  'preview_url': 'https://p.scdn.co/mp3-preview/a95a22001e0e048524e8dfec65478d029cdd3396?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 9,
  'type': 'track',
  'uri': 'spotify:track:3eE6IderHf7lnqOorqiNVK'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2iS4pBIiQf4sCTJLZ5n8dy'},
   'href': 'https://api.spotify.com/v1/albums/2iS4pBIiQf4sCTJLZ5n8dy',
   'id': '2iS4pBIiQf4sCTJLZ5n8dy',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dbc606d7a57e551c5b9d4ee3',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e02dbc606d7a57e551c5b9d4ee3',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d00004851dbc606d7a57e551c5b9d4ee3',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'SMILE! :D',
   'release_date': '2024-07-26',
   'release_date_precision': 'day',
   'total_tracks': 10,
   'type': 'album',
   'uri': 'spotify:album:2iS4pBIiQf4sCTJLZ5n8dy'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 388800,
  'explicit': True,
  'external_ids': {'isrc': 'USQE92400083'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/3RdUgst4llmyJkVtNaqHGv'},
  'href': 'https://api.spotify.com/v1/tracks/3RdUgst4llmyJkVtNaqHGv',
  'id': '3RdUgst4llmyJkVtNaqHGv',
  'is_local': False,
  'is_playable': True,
  'name': 'Russian Roulette',
  'popularity': 55,
  'preview_url': 'https://p.scdn.co/mp3-preview/de199e6c7a09d9df55c4fb19a3b9f1c423a79fb8?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 3,
  'type': 'track',
  'uri': 'spotify:track:3RdUgst4llmyJkVtNaqHGv'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD'},
   'href': 'https://api.spotify.com/v1/albums/7AJPV0L05IyIBid97AvwVD',
   'id': '7AJPV0L05IyIBid97AvwVD',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731f675e7b8bae408653346dd9',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e021f675e7b8bae408653346dd9',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d000048511f675e7b8bae408653346dd9',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'Worlds',
   'release_date': '2014-08-12',
   'release_date_precision': 'day',
   'total_tracks': 12,
   'type': 'album',
   'uri': 'spotify:album:7AJPV0L05IyIBid97AvwVD'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 350690,
  'explicit': False,
  'external_ids': {'isrc': 'USUG11400374'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/1JY6B9ILvmRla2IKKRZvnH'},
  'href': 'https://api.spotify.com/v1/tracks/1JY6B9ILvmRla2IKKRZvnH',
  'id': '1JY6B9ILvmRla2IKKRZvnH',
  'is_local': False,
  'is_playable': True,
  'name': 'Sad Machine',
  'popularity': 55,
  'preview_url': 'https://p.scdn.co/mp3-preview/cdc2417a6df9dd1e30666bb6fc9d1f8d9c15c0a9?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 2,
  'type': 'track',
  'uri': 'spotify:track:1JY6B9ILvmRla2IKKRZvnH'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
     'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
     'id': '3dz0NnIZhtKKeXZxLOxCam',
     'name': 'Porter Robinson',
     'type': 'artist',
     'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/4Hjqdhj5rh816i1dfcUEaM'},
   'href': 'https://api.spotify.com/v1/albums/4Hjqdhj5rh816i1dfcUEaM',
   'id': '4Hjqdhj5rh816i1dfcUEaM',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2737d6ac8b4a84ad4b342050d87',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e027d6ac8b4a84ad4b342050d87',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d000048517d6ac8b4a84ad4b342050d87',
     'width': 64,
     'height': 64}],
   'is_playable': True,
   'name': 'Nurture',
   'release_date': '2021-04-23',
   'release_date_precision': 'day',
   'total_tracks': 14,
   'type': 'album',
   'uri': 'spotify:album:4Hjqdhj5rh816i1dfcUEaM'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},
    'href': 'https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam',
    'id': '3dz0NnIZhtKKeXZxLOxCam',
    'name': 'Porter Robinson',
    'type': 'artist',
    'uri': 'spotify:artist:3dz0NnIZhtKKeXZxLOxCam'}],
  'disc_number': 1,
  'duration_ms': 309985,
  'explicit': False,
  'external_ids': {'isrc': 'USQE92000004'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/5lXNcc8QeM9KpAWNHAL0iS'},
  'href': 'https://api.spotify.com/v1/tracks/5lXNcc8QeM9KpAWNHAL0iS',
  'id': '5lXNcc8QeM9KpAWNHAL0iS',
  'is_local': False,
  'is_playable': True,
  'name': 'Look at the Sky',
  'popularity': 55,
  'preview_url': 'https://p.scdn.co/mp3-preview/6098cb45f301bcfa292daf422e786ecc7460f81d?cid=951782aa84c243559e2e7640422391d3',
  'track_number': 2,
  'type': 'track',
  'uri': 'spotify:track:5lXNcc8QeM9KpAWNHAL0iS'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam'},

## Get audio features for the top tracks
https://developer.spotify.com/documentation/web-api/reference/get-audio-features

In [24]:
track_info_list = []

for track in top_tracks:
    track_id = track['id']

    audio_features_url = f'https://api.spotify.com/v1/audio-features/{track_id}'

    response = requests.get(audio_features_url, headers = auth_headers)
    audio_features_response = response.json()
    print(f'audio_features_response: {audio_features_response}')
    track_info = {
        'track_name': track['name'],
        'artist': ', '.join([artist['name'] for artist in track['artists']]),
        'album': track['album']['name'],
        'track_uri': track['uri'],
        'danceability': audio_features_response['danceability'],
        'energy': audio_features_response['energy'],
        'valence': audio_features_response['valence'],
        'popularity': track['popularity']
    }
    track_info_list.append(track_info)

audio_features_response: {'danceability': 0.477, 'energy': 0.796, 'key': 0, 'loudness': -4.499, 'mode': 1, 'speechiness': 0.0369, 'acousticness': 0.00293, 'instrumentalness': 0, 'liveness': 0.184, 'valence': 0.27, 'tempo': 99.859, 'type': 'audio_features', 'id': '2ewEh7LuvToYyGHq7yT8N1', 'uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1', 'track_href': 'https://api.spotify.com/v1/tracks/2ewEh7LuvToYyGHq7yT8N1', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2ewEh7LuvToYyGHq7yT8N1', 'duration_ms': 218965, 'time_signature': 4}
audio_features_response: {'danceability': 0.464, 'energy': 0.701, 'key': 0, 'loudness': -2.591, 'mode': 0, 'speechiness': 0.0395, 'acousticness': 0.000199, 'instrumentalness': 0, 'liveness': 0.0484, 'valence': 0.277, 'tempo': 147.944, 'type': 'audio_features', 'id': '5iyuwVaMliMdloOzSBxohv', 'uri': 'spotify:track:5iyuwVaMliMdloOzSBxohv', 'track_href': 'https://api.spotify.com/v1/tracks/5iyuwVaMliMdloOzSBxohv', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/5iyuwVaMliMdloOzSBxohv', 'duration_ms': 237568, 'time_signature': 4}
audio_features_response: {'danceability': 0.55, 'energy': 0.648, 'key': 7, 'loudness': -6.542, 'mode': 1, 'speechiness': 0.0309, 'acousticness': 0.0191, 'instrumentalness': 0, 'liveness': 0.0999, 'valence': 0.323, 'tempo': 156.957, 'type': 'audio_features', 'id': '3WBRfkOozHEsG0hbrBzwlm', 'uri': 'spotify:track:3WBRfkOozHEsG0hbrBzwlm', 'track_href': 'https://api.spotify.com/v1/tracks/3WBRfkOozHEsG0hbrBzwlm', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3WBRfkOozHEsG0hbrBzwlm', 'duration_ms': 202821, 'time_signature': 4}
audio_features_response: {'danceability': 0.444, 'energy': 0.35, 'key': 9, 'loudness': -7.194, 'mode': 1, 'speechiness': 0.0483, 'acousticness': 0.453, 'instrumentalness': 0.109, 'liveness': 0.0824, 'valence': 0.0973, 'tempo': 95.979, 'type': 'audio_features', 'id': '786ymAh5BmHoIpvjyrvjXk', 'uri': 'spotify:track:786ymAh5BmHoIpvjyrvjXk', 'track_href': 'https://api.spotify.com/v1/tracks/786ymAh5BmHoIpvjyrvjXk', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/786ymAh5BmHoIpvjyrvjXk', 'duration_ms': 328507, 'time_signature': 3}
audio_features_response: {'danceability': 0.554, 'energy': 0.741, 'key': 6, 'loudness': -3.782, 'mode': 1, 'speechiness': 0.0342, 'acousticness': 0.00109, 'instrumentalness': 0, 'liveness': 0.0775, 'valence': 0.332, 'tempo': 87.011, 'type': 'audio_features', 'id': '6yfY7OdAz4VEOjPUOP3yzN', 'uri': 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN', 'track_href': 'https://api.spotify.com/v1/tracks/6yfY7OdAz4VEOjPUOP3yzN', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6yfY7OdAz4VEOjPUOP3yzN', 'duration_ms': 168278, 'time_signature': 4}
audio_features_response: {'danceability': 0.608, 'energy': 0.838, 'key': 6, 'loudness': -3.813, 'mode': 1, 'speechiness': 0.0309, 'acousticness': 0.159, 'instrumentalness': 1.31e-06, 'liveness': 0.0877, 'valence': 0.631, 'tempo': 98.048, 'type': 'audio_features', 'id': '3eE6IderHf7lnqOorqiNVK', 'uri': 'spotify:track:3eE6IderHf7lnqOorqiNVK', 'track_href': 'https://api.spotify.com/v1/tracks/3eE6IderHf7lnqOorqiNVK', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3eE6IderHf7lnqOorqiNVK', 'duration_ms': 199668, 'time_signature': 4}
audio_features_response: {'danceability': 0.55, 'energy': 0.78, 'key': 10, 'loudness': -5.393, 'mode': 1, 'speechiness': 0.148, 'acousticness': 0.0491, 'instrumentalness': 0, 'liveness': 0.379, 'valence': 0.22, 'tempo': 149.982, 'type': 'audio_features', 'id': '3RdUgst4llmyJkVtNaqHGv', 'uri': 'spotify:track:3RdUgst4llmyJkVtNaqHGv', 'track_href': 'https://api.spotify.com/v1/tracks/3RdUgst4llmyJkVtNaqHGv', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3RdUgst4llmyJkVtNaqHGv', 'duration_ms': 388800, 'time_signature': 4}
audio_features_response: {'danceability': 0.47, 'energy': 0.706, 'key': 0, 'loudness': -4.902, 'mode': 0, 'speechiness': 0.0322, 'acousticness': 0.034, 'instrumentalness': 1.31e-06, 'liveness': 0.0726, 'valence': 0.327, 'tempo': 88.519, 'type': 'audio_features', 'id': '1JY6B9ILvmRla2IKKRZvnH', 'uri': 'spotify:track:1JY6B9ILvmRla2IKKRZvnH', 'track_href': 'https://api.spotify.com/v1/tracks/1JY6B9ILvmRla2IKKRZvnH', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/1JY6B9ILvmRla2IKKRZvnH', 'duration_ms': 350690, 'time_signature': 4}
audio_features_response: {'danceability': 0.568, 'energy': 0.564, 'key': 6, 'loudness': -8.231, 'mode': 1, 'speechiness': 0.0273, 'acousticness': 0.0105, 'instrumentalness': 0.000127, 'liveness': 0.0766, 'valence': 0.385, 'tempo': 115.059, 'type': 'audio_features', 'id': '5lXNcc8QeM9KpAWNHAL0iS', 'uri': 'spotify:track:5lXNcc8QeM9KpAWNHAL0iS', 'track_href': 'https://api.spotify.com/v1/tracks/5lXNcc8QeM9KpAWNHAL0iS', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/5lXNcc8QeM9KpAWNHAL0iS', 'duration_ms': 309986, 'time_signature': 4}
audio_features_response: {'danceability': 0.812, 'energy': 0.418, 'key': 11, 'loudness': -5.735, 'mode': 1, 'speechiness': 0.038, 'acousticness': 0.000327, 'instrumentalness': 0, 'liveness': 0.0772, 'valence': 0.85, 'tempo': 110.804, 'type': 'audio_features', 'id': '1VD9irJC3S3cyKrYoq9ymL', 'uri': 'spotify:track:1VD9irJC3S3cyKrYoq9ymL', 'track_href': 'https://api.spotify.com/v1/tracks/1VD9irJC3S3cyKrYoq9ymL', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/1VD9irJC3S3cyKrYoq9ymL', 'duration_ms': 148782, 'time_signature': 4}
audio_features_response: {'danceability': 0.477, 'energy': 0.796, 'key': 0, 'loudness': -4.499, 'mode': 1, 'speechiness': 0.0369, 'acousticness': 0.00293, 'instrumentalness': 0, 'liveness': 0.184, 'valence': 0.27, 'tempo': 99.859, 'type': 'audio_features', 'id': '2ewEh7LuvToYyGHq7yT8N1', 'uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1', 'track_href': 'https://api.spotify.com/v1/tracks/2ewEh7LuvToYyGHq7yT8N1', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2ewEh7LuvToYyGHq7yT8N1', 'duration_ms': 218965, 'time_signature': 4}
audio_features_response: {'danceability': 0.511, 'energy': 0.718, 'key': 11, 'loudness': -7.46, 'mode': 1, 'speechiness': 0.0367, 'acousticness': 0.00454, 'instrumentalness': 9.61e-05, 'liveness': 0.0913, 'valence': 0.274, 'tempo': 106.016, 'type': 'audio_features', 'id': '5wM6LOw2U6XeIFHfsgI6wU', 'uri': 'spotify:track:5wM6LOw2U6XeIFHfsgI6wU', 'track_href': 'https://api.spotify.com/v1/tracks/5wM6LOw2U6XeIFHfsgI6wU', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/5wM6LOw2U6XeIFHfsgI6wU', 'duration_ms': 214104, 'time_signature': 4}
audio_features_response: {'danceability': 0.49, 'energy': 0.914, 'key': 10, 'loudness': -3.202, 'mode': 1, 'speechiness': 0.167, 'acousticness': 0.0227, 'instrumentalness': 0, 'liveness': 0.793, 'valence': 0.241, 'tempo': 100.1, 'type': 'audio_features', 'id': '4PTPZeJlK1rYlYr6bf11hk', 'uri': 'spotify:track:4PTPZeJlK1rYlYr6bf11hk', 'track_href': 'https://api.spotify.com/v1/tracks/4PTPZeJlK1rYlYr6bf11hk', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4PTPZeJlK1rYlYr6bf11hk', 'duration_ms': 192720, 'time_signature': 4}
audio_features_response: {'danceability': 0.417, 'energy': 0.859, 'key': 7, 'loudness': -3.169, 'mode': 0, 'speechiness': 0.0484, 'acousticness': 0.00612, 'instrumentalness': 2.41e-06, 'liveness': 0.175, 'valence': 0.179, 'tempo': 92.078, 'type': 'audio_features', 'id': '4ATmY1hv93ehw77LrIdbEh', 'uri': 'spotify:track:4ATmY1hv93ehw77LrIdbEh', 'track_href': 'https://api.spotify.com/v1/tracks/4ATmY1hv93ehw77LrIdbEh', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4ATmY1hv93ehw77LrIdbEh', 'duration_ms': 204853, 'time_signature': 4}
audio_features_response: {'danceability': 0.669, 'energy': 0.926, 'key': 2, 'loudness': -5.02, 'mode': 1, 'speechiness': 0.0686, 'acousticness': 0.0121, 'instrumentalness': 0.211, 'liveness': 0.835, 'valence': 0.508, 'tempo': 129.955, 'type': 'audio_features', 'id': '1IzM5hoLr4bUq57FOrWXQ2', 'uri': 'spotify:track:1IzM5hoLr4bUq57FOrWXQ2', 'track_href': 'https://api.spotify.com/v1/tracks/1IzM5hoLr4bUq57FOrWXQ2', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/1IzM5hoLr4bUq57FOrWXQ2', 'duration_ms': 150453, 'time_signature': 4}
audio_features_response: {'danceability': 0.668, 'energy': 0.764, 'key': 8, 'loudness': -4.277, 'mode': 0, 'speechiness': 0.0487, 'acousticness': 0.025, 'instrumentalness': 0, 'liveness': 0.314, 'valence': 0.685, 'tempo': 106.036, 'type': 'audio_features', 'id': '3ArdPRbscsYB2uI70AzpuG', 'uri': 'spotify:track:3ArdPRbscsYB2uI70AzpuG', 'track_href': 'https://api.spotify.com/v1/tracks/3ArdPRbscsYB2uI70AzpuG', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3ArdPRbscsYB2uI70AzpuG', 'duration_ms': 204613, 'time_signature': 4}
audio_features_response: {'danceability': 0.52, 'energy': 0.825, 'key': 7, 'loudness': -2.171, 'mode': 0, 'speechiness': 0.046, 'acousticness': 0.00162, 'instrumentalness': 0, 'liveness': 0.711, 'valence': 0.264, 'tempo': 125.011, 'type': 'audio_features', 'id': '36HA2woC1glnLa4vqWY3IC', 'uri': 'spotify:track:36HA2woC1glnLa4vqWY3IC', 'track_href': 'https://api.spotify.com/v1/tracks/36HA2woC1glnLa4vqWY3IC', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/36HA2woC1glnLa4vqWY3IC', 'duration_ms': 233987, 'time_signature': 4}
audio_features_response: {'danceability': 0.546, 'energy': 0.852, 'key': 1, 'loudness': -2.445, 'mode': 1, 'speechiness': 0.102, 'acousticness': 0.00592, 'instrumentalness': 0, 'liveness': 0.159, 'valence': 0.558, 'tempo': 112.183, 'type': 'audio_features', 'id': '3rsq3qtqNBId48c0IVraTS', 'uri': 'spotify:track:3rsq3qtqNBId48c0IVraTS', 'track_href': 'https://api.spotify.com/v1/tracks/3rsq3qtqNBId48c0IVraTS', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3rsq3qtqNBId48c0IVraTS', 'duration_ms': 249440, 'time_signature': 4}
audio_features_response: {'danceability': 0.714, 'energy': 0.811, 'key': 0, 'loudness': -3.69, 'mode': 0, 'speechiness': 0.107, 'acousticness': 0.0892, 'instrumentalness': 0, 'liveness': 0.0979, 'valence': 0.736, 'tempo': 115.0, 'type': 'audio_features', 'id': '7oXWYW58qy9VEbsdtUYqI6', 'uri': 'spotify:track:7oXWYW58qy9VEbsdtUYqI6', 'track_href': 'https://api.spotify.com/v1/tracks/7oXWYW58qy9VEbsdtUYqI6', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/7oXWYW58qy9VEbsdtUYqI6', 'duration_ms': 161772, 'time_signature': 4}
audio_features_response: {'danceability': 0.599, 'energy': 0.635, 'key': 10, 'loudness': -6.5, 'mode': 0, 'speechiness': 0.103, 'acousticness': 0.00988, 'instrumentalness': 6.39e-05, 'liveness': 0.368, 'valence': 0.798, 'tempo': 95.919, 'type': 'audio_features', 'id': '36X1P3v7N1dv06bh2aPtMF', 'uri': 'spotify:track:36X1P3v7N1dv06bh2aPtMF', 'track_href': 'https://api.spotify.com/v1/tracks/36X1P3v7N1dv06bh2aPtMF', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/36X1P3v7N1dv06bh2aPtMF', 'duration_ms': 174683, 'time_signature': 4}
audio_features_response: {'danceability': 0.57, 'energy': 0.763, 'key': 1, 'loudness': -4.137, 'mode': 1, 'speechiness': 0.0573, 'acousticness': 0.0857, 'instrumentalness': 2.49e-06, 'liveness': 0.0932, 'valence': 0.43, 'tempo': 150.088, 'type': 'audio_features', 'id': '6jq6rcOikCZAmjliAgAmfT', 'uri': 'spotify:track:6jq6rcOikCZAmjliAgAmfT', 'track_href': 'https://api.spotify.com/v1/tracks/6jq6rcOikCZAmjliAgAmfT', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6jq6rcOikCZAmjliAgAmfT', 'duration_ms': 239853, 'time_signature': 4}
audio_features_response: {'danceability': 0.747, 'energy': 0.491, 'key': 6, 'loudness': -6.043, 'mode': 1, 'speechiness': 0.0639, 'acousticness': 0.197, 'instrumentalness': 1.77e-05, 'liveness': 0.0837, 'valence': 0.827, 'tempo': 145.034, 'type': 'audio_features', 'id': '7uSZPbd8DxdkmSauCKnITY', 'uri': 'spotify:track:7uSZPbd8DxdkmSauCKnITY', 'track_href': 'https://api.spotify.com/v1/tracks/7uSZPbd8DxdkmSauCKnITY', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/7uSZPbd8DxdkmSauCKnITY', 'duration_ms': 266483, 'time_signature': 4}
audio_features_response: {'danceability': 0.626, 'energy': 0.902, 'key': 7, 'loudness': -3.749, 'mode': 0, 'speechiness': 0.073, 'acousticness': 0.0058, 'instrumentalness': 0.0199, 'liveness': 0.142, 'valence': 0.395, 'tempo': 109.981, 'type': 'audio_features', 'id': '2AHd1SRo5rAFvJOCEwLyTi', 'uri': 'spotify:track:2AHd1SRo5rAFvJOCEwLyTi', 'track_href': 'https://api.spotify.com/v1/tracks/2AHd1SRo5rAFvJOCEwLyTi', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2AHd1SRo5rAFvJOCEwLyTi', 'duration_ms': 168545, 'time_signature': 4}
audio_features_response: {'danceability': 0.536, 'energy': 0.865, 'key': 2, 'loudness': -6.988, 'mode': 1, 'speechiness': 0.129, 'acousticness': 0.00109, 'instrumentalness': 0.000239, 'liveness': 0.119, 'valence': 0.163, 'tempo': 132.974, 'type': 'audio_features', 'id': '7LAFTet7LRO1ydBaqNRgr9', 'uri': 'spotify:track:7LAFTet7LRO1ydBaqNRgr9', 'track_href': 'https://api.spotify.com/v1/tracks/7LAFTet7LRO1ydBaqNRgr9', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/7LAFTet7LRO1ydBaqNRgr9', 'duration_ms': 210564, 'time_signature': 4}
audio_features_response: {'danceability': 0.572, 'energy': 0.69, 'key': 11, 'loudness': -4.939, 'mode': 0, 'speechiness': 0.0396, 'acousticness': 0.513, 'instrumentalness': 4.83e-05, 'liveness': 0.148, 'valence': 0.347, 'tempo': 155.134, 'type': 'audio_features', 'id': '7kZVirTc3V6d4YWtu6RaAu', 'uri': 'spotify:track:7kZVirTc3V6d4YWtu6RaAu', 'track_href': 'https://api.spotify.com/v1/tracks/7kZVirTc3V6d4YWtu6RaAu', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/7kZVirTc3V6d4YWtu6RaAu', 'duration_ms': 260903, 'time_signature': 4}
audio_features_response: {'danceability': 0.314, 'energy': 0.727, 'key': 7, 'loudness': -6.773, 'mode': 1, 'speechiness': 0.0712, 'acousticness': 0.379, 'instrumentalness': 0.000257, 'liveness': 0.392, 'valence': 0.232, 'tempo': 134.559, 'type': 'audio_features', 'id': '5BzLCBy61N1a6la0MVtueV', 'uri': 'spotify:track:5BzLCBy61N1a6la0MVtueV', 'track_href': 'https://api.spotify.com/v1/tracks/5BzLCBy61N1a6la0MVtueV', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/5BzLCBy61N1a6la0MVtueV', 'duration_ms': 172847, 'time_signature': 4}
audio_features_response: {'danceability': 0.401, 'energy': 0.786, 'key': 1, 'loudness': -6.455, 'mode': 0, 'speechiness': 0.055, 'acousticness': 0.367, 'instrumentalness': 0.0065, 'liveness': 0.134, 'valence': 0.264, 'tempo': 134.87, 'type': 'audio_features', 'id': '6VpRQDOM7nQ6viuVUSXWGn', 'uri': 'spotify:track:6VpRQDOM7nQ6viuVUSXWGn', 'track_href': 'https://api.spotify.com/v1/tracks/6VpRQDOM7nQ6viuVUSXWGn', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6VpRQDOM7nQ6viuVUSXWGn', 'duration_ms': 201199, 'time_signature': 4}
audio_features_response: {'danceability': 0.458, 'energy': 0.686, 'key': 9, 'loudness': -6.599, 'mode': 1, 'speechiness': 0.0729, 'acousticness': 0.36, 'instrumentalness': 0.000447, 'liveness': 0.319, 'valence': 0.362, 'tempo': 171.787, 'type': 'audio_features', 'id': '4nBTt4n122lScgQwHzKVCV', 'uri': 'spotify:track:4nBTt4n122lScgQwHzKVCV', 'track_href': 'https://api.spotify.com/v1/tracks/4nBTt4n122lScgQwHzKVCV', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4nBTt4n122lScgQwHzKVCV', 'duration_ms': 181232, 'time_signature': 4}
audio_features_response: {'danceability': 0.608, 'energy': 0.772, 'key': 9, 'loudness': -5.351, 'mode': 1, 'speechiness': 0.0488, 'acousticness': 0.0391, 'instrumentalness': 0, 'liveness': 0.113, 'valence': 0.339, 'tempo': 132.964, 'type': 'audio_features', 'id': '3lqfTqap6aFMlYGEOyDZvt', 'uri': 'spotify:track:3lqfTqap6aFMlYGEOyDZvt', 'track_href': 'https://api.spotify.com/v1/tracks/3lqfTqap6aFMlYGEOyDZvt', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3lqfTqap6aFMlYGEOyDZvt', 'duration_ms': 150226, 'time_signature': 4}
audio_features_response: {'danceability': 0.591, 'energy': 0.569, 'key': 8, 'loudness': -7.089, 'mode': 1, 'speechiness': 0.16, 'acousticness': 0.208, 'instrumentalness': 0.00357, 'liveness': 0.232, 'valence': 0.304, 'tempo': 149.913, 'type': 'audio_features', 'id': '38q117S1yZJorvr6hvMhkT', 'uri': 'spotify:track:38q117S1yZJorvr6hvMhkT', 'track_href': 'https://api.spotify.com/v1/tracks/38q117S1yZJorvr6hvMhkT', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/38q117S1yZJorvr6hvMhkT', 'duration_ms': 220800, 'time_signature': 4}
audio_features_response: {'danceability': 0.695, 'energy': 0.689, 'key': 8, 'loudness': -6.213, 'mode': 0, 'speechiness': 0.0718, 'acousticness': 0.307, 'instrumentalness': 0, 'liveness': 0.143, 'valence': 0.496, 'tempo': 110.952, 'type': 'audio_features', 'id': '4ZPwjq0CdxbWFNycxnSUJc', 'uri': 'spotify:track:4ZPwjq0CdxbWFNycxnSUJc', 'track_href': 'https://api.spotify.com/v1/tracks/4ZPwjq0CdxbWFNycxnSUJc', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4ZPwjq0CdxbWFNycxnSUJc', 'duration_ms': 166487, 'time_signature': 4}
audio_features_response: {'danceability': 0.619, 'energy': 0.714, 'key': 0, 'loudness': -5.39, 'mode': 0, 'speechiness': 0.118, 'acousticness': 0.0284, 'instrumentalness': 0, 'liveness': 0.273, 'valence': 0.432, 'tempo': 109.949, 'type': 'audio_features', 'id': '7zPAsqqz9M5qcpG42YUiug', 'uri': 'spotify:track:7zPAsqqz9M5qcpG42YUiug', 'track_href': 'https://api.spotify.com/v1/tracks/7zPAsqqz9M5qcpG42YUiug', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/7zPAsqqz9M5qcpG42YUiug', 'duration_ms': 216017, 'time_signature': 4}
audio_features_response: {'danceability': 0.659, 'energy': 0.672, 'key': 4, 'loudness': -7.56, 'mode': 0, 'speechiness': 0.0975, 'acousticness': 0.0535, 'instrumentalness': 3.37e-05, 'liveness': 0.0941, 'valence': 0.289, 'tempo': 110.04, 'type': 'audio_features', 'id': '5gneV1qwaIndUU4aZ3uhXP', 'uri': 'spotify:track:5gneV1qwaIndUU4aZ3uhXP', 'track_href': 'https://api.spotify.com/v1/tracks/5gneV1qwaIndUU4aZ3uhXP', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/5gneV1qwaIndUU4aZ3uhXP', 'duration_ms': 213818, 'time_signature': 4}
audio_features_response: {'danceability': 0.507, 'energy': 0.864, 'key': 7, 'loudness': -3.934, 'mode': 0, 'speechiness': 0.169, 'acousticness': 0.185, 'instrumentalness': 0, 'liveness': 0.161, 'valence': 0.476, 'tempo': 155.924, 'type': 'audio_features', 'id': '2P8MOT07PrPiTjqNPKWVsp', 'uri': 'spotify:track:2P8MOT07PrPiTjqNPKWVsp', 'track_href': 'https://api.spotify.com/v1/tracks/2P8MOT07PrPiTjqNPKWVsp', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2P8MOT07PrPiTjqNPKWVsp', 'duration_ms': 193683, 'time_signature': 4}
audio_features_response: {'danceability': 0.614, 'energy': 0.655, 'key': 7, 'loudness': -6.581, 'mode': 1, 'speechiness': 0.145, 'acousticness': 0.115, 'instrumentalness': 0, 'liveness': 0.172, 'valence': 0.641, 'tempo': 159.804, 'type': 'audio_features', 'id': '63psBh1jACfpWZtpZQZbVM', 'uri': 'spotify:track:63psBh1jACfpWZtpZQZbVM', 'track_href': 'https://api.spotify.com/v1/tracks/63psBh1jACfpWZtpZQZbVM', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/63psBh1jACfpWZtpZQZbVM', 'duration_ms': 198016, 'time_signature': 4}
audio_features_response: {'danceability': 0.244, 'energy': 0.721, 'key': 1, 'loudness': -4.715, 'mode': 1, 'speechiness': 0.0354, 'acousticness': 0.0272, 'instrumentalness': 0, 'liveness': 0.145, 'valence': 0.114, 'tempo': 98.825, 'type': 'audio_features', 'id': '4H1FdAyWZBNzwcHFQYeGy6', 'uri': 'spotify:track:4H1FdAyWZBNzwcHFQYeGy6', 'track_href': 'https://api.spotify.com/v1/tracks/4H1FdAyWZBNzwcHFQYeGy6', 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4H1FdAyWZBNzwcHFQYeGy6', 'duration_ms': 241350, 'time_signature': 4}

In [25]:
track_info_list

[{'track_name': 'Shelter',
  'artist': 'Porter Robinson, Madeon',
  'album': 'Shelter',
  'track_uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1',
  'danceability': 0.477,
  'energy': 0.796,
  'valence': 0.27,
  'popularity': 61},
 {'track_name': 'Cheerleader',
  'artist': 'Porter Robinson',
  'album': 'SMILE! :D',
  'track_uri': 'spotify:track:5iyuwVaMliMdloOzSBxohv',
  'danceability': 0.464,
  'energy': 0.701,
  'valence': 0.277,
  'popularity': 58},
 {'track_name': 'Everything Goes On',
  'artist': 'Porter Robinson, League of Legends',
  'album': 'Everything Goes On',
  'track_uri': 'spotify:track:3WBRfkOozHEsG0hbrBzwlm',
  'danceability': 0.55,
  'energy': 0.648,
  'valence': 0.323,
  'popularity': 60},
 {'track_name': 'Goodbye To A World',
  'artist': 'Porter Robinson',
  'album': 'Worlds',
  'track_uri': 'spotify:track:786ymAh5BmHoIpvjyrvjXk',
  'danceability': 0.444,
  'energy': 0.35,
  'valence': 0.0973,
  'popularity': 58},
 {'track_name': 'Knock Yourself Out XD',
  'artist': 'Porter Robinson',
  'album': 'SMILE! :D',
  'track_uri': 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN',
  'danceability': 0.554,
  'energy': 0.741,
  'valence': 0.332,
  'popularity': 56},
 {'track_name': 'Is There Really No Happiness?',
  'artist': 'Porter Robinson',
  'album': 'SMILE! :D',
  'track_uri': 'spotify:track:3eE6IderHf7lnqOorqiNVK',
  'danceability': 0.608,
  'energy': 0.838,
  'valence': 0.631,
  'popularity': 57},
 {'track_name': 'Russian Roulette',
  'artist': 'Porter Robinson',
  'album': 'SMILE! :D',
  'track_uri': 'spotify:track:3RdUgst4llmyJkVtNaqHGv',
  'danceability': 0.55,
  'energy': 0.78,
  'valence': 0.22,
  'popularity': 55},
 {'track_name': 'Sad Machine',
  'artist': 'Porter Robinson',
  'album': 'Worlds',
  'track_uri': 'spotify:track:1JY6B9ILvmRla2IKKRZvnH',
  'danceability': 0.47,
  'energy': 0.706,
  'valence': 0.327,
  'popularity': 55},
 {'track_name': 'Look at the Sky',
  'artist': 'Porter Robinson',
  'album': 'Nurture',
  'track_uri': 'spotify:track:5lXNcc8QeM9KpAWNHAL0iS',
  'danceability': 0.568,
  'energy': 0.564,
  'valence': 0.385,
  'popularity': 55},
 {'track_name': 'Perfect Pinterest Garden',
  'artist': 'Porter Robinson',
  'album': 'SMILE! :D',
  'track_uri': 'spotify:track:1VD9irJC3S3cyKrYoq9ymL',
  'danceability': 0.812,
  'energy': 0.418,
  'valence': 0.85,
  'popularity': 55},
 {'track_name': 'Shelter',
  'artist': 'Porter Robinson, Madeon',
  'album': 'Shelter',
  'track_uri': 'spotify:track:2ewEh7LuvToYyGHq7yT8N1',
  'danceability': 0.477,
  'energy': 0.796,
  'valence': 0.27,
  'popularity': 61},
 {'track_name': 'Love You Back',
  'artist': 'Madeon',
  'album': 'Love You Back',
  'track_uri': 'spotify:track:5wM6LOw2U6XeIFHfsgI6wU',
  'danceability': 0.511,
  'energy': 0.718,
  'valence': 0.274,
  'popularity': 50},
 {'track_name': "You're On (feat. Kyan)",
  'artist': 'Madeon, Kyan',
  'album': 'Adventure (Deluxe)',
  'track_uri': 'spotify:track:4PTPZeJlK1rYlYr6bf11hk',
  'danceability': 0.49,
  'energy': 0.914,
  'valence': 0.241,
  'popularity': 47},
 {'track_name': 'Finale (feat. Nicholas Petricca)',
  'artist': 'Madeon, Nicholas Petricca',
  'album': 'Adventure (Deluxe)',
  'track_uri': 'spotify:track:4ATmY1hv93ehw77LrIdbEh',
  'danceability': 0.417,
  'energy': 0.859,
  'valence': 0.179,
  'popularity': 43},
 {'track_name': 'Believe It',
  'artist': 'Louis The Child, Madeon',
  'album': 'The Sun Comes Up',
  'track_uri': 'spotify:track:1IzM5hoLr4bUq57FOrWXQ2',
  'danceability': 0.669,
  'energy': 0.926,
  'valence': 0.508,
  'popularity': 46},
 {'track_name': 'All My Friends',
  'artist': 'Madeon',
  'album': 'Good Faith',
  'track_uri': 'spotify:track:3ArdPRbscsYB2uI70AzpuG',
  'danceability': 0.668,
  'energy': 0.764,
  'valence': 0.685,
  'popularity': 46},
 {'track_name': 'The City',
  'artist': 'Madeon',
  'album': 'Adventure (Deluxe)',
  'track_uri': 'spotify:track:36HA2woC1glnLa4vqWY3IC',
  'danceability': 0.52,
  'energy': 0.825,
  'valence': 0.264,
  'popularity': 43},
 {'track_name': 'Pay No Mind (feat. Passion Pit)',
  'artist': 'Madeon, Passion Pit',
  'album': 'Adventure (Deluxe)',
  'track_uri': 'spotify:track:3rsq3qtqNBId48c0IVraTS',
  'danceability': 0.546,
  'energy': 0.852,
  'valence': 0.558,
  'popularity': 44},
 {'track_name': 'All Ur Luv',
  'artist': 'Wavedash, Madeon, Toro y Moi',
  'album': 'Tempo',
  'track_uri': 'spotify:track:7oXWYW58qy9VEbsdtUYqI6',
  'danceability': 0.714,
  'energy': 0.811,
  'valence': 0.736,
  'popularity': 38},
 {'track_name': 'No Fear No More (Remix)',
  'artist': 'Madeon, EARTHGANG',
  'album': 'No Fear No More (Remix)',
  'track_uri': 'spotify:track:36X1P3v7N1dv06bh2aPtMF',
  'danceability': 0.599,
  'energy': 0.635,
  'valence': 0.798,
  'popularity': 43},
 {'track_name': 'Light',
  'artist': 'San Holo',
  'album': 'Light',
  'track_uri': 'spotify:track:6jq6rcOikCZAmjliAgAmfT',
  'danceability': 0.57,
  'energy': 0.763,
  'valence': 0.43,
  'popularity': 56},
 {'track_name': 'We Rise',
  'artist': 'San Holo',
  'album': 'We Rise',
  'track_uri': 'spotify:track:7uSZPbd8DxdkmSauCKnITY',
  'danceability': 0.747,
  'energy': 0.491,
  'valence': 0.827,
  'popularity': 51},
 {'track_name': 'BRING BACK THE COLOR',
  'artist': 'San Holo, AURORA',
  'album': 'EXISTENTIAL DANCE MUSIC',
  'track_uri': 'spotify:track:2AHd1SRo5rAFvJOCEwLyTi',
  'danceability': 0.626,
  'energy': 0.902,
  'valence': 0.395,
  'popularity': 47},
 {'track_name': 'feel again',
  'artist': 'San Holo, Tchami',
  'album': 'feel again',
  'track_uri': 'spotify:track:7LAFTet7LRO1ydBaqNRgr9',
  'danceability': 0.536,
  'energy': 0.865,
  'valence': 0.163,
  'popularity': 49},
 {'track_name': 'lift me from the ground',
  'artist': 'San Holo, Sofie Winterson',
  'album': 'album1',
  'track_uri': 'spotify:track:7kZVirTc3V6d4YWtu6RaAu',
  'danceability': 0.572,
  'energy': 0.69,
  'valence': 0.347,
  'popularity': 49},
 {'track_name': 'disappear',
  'artist': 'San Holo, artemis orion, dobi',
  'album': 'disappear',
  'track_uri': 'spotify:track:5BzLCBy61N1a6la0MVtueV',
  'danceability': 0.314,
  'energy': 0.727,
  'valence': 0.232,
  'popularity': 48},
 {'track_name': 'We Will Meet Again',
  'artist': 'San Holo, Jai Wolf',
  'album': 'We Will Meet Again',
  'track_uri': 'spotify:track:6VpRQDOM7nQ6viuVUSXWGn',
  'danceability': 0.401,
  'energy': 0.786,
  'valence': 0.264,
  'popularity': 45},
 {'track_name': 'what is life?',
  'artist': 'San Holo, Bipolar Sunshine',
  'album': 'what is life?',
  'track_uri': 'spotify:track:4nBTt4n122lScgQwHzKVCV',
  'danceability': 0.458,
  'energy': 0.686,
  'valence': 0.362,
  'popularity': 42},
 {'track_name': 'GLOW (feat. Au/Ra)',
  'artist': 'San Holo, Au/Ra',
  'album': 'GLOW (feat. Au/Ra)',
  'track_uri': 'spotify:track:3lqfTqap6aFMlYGEOyDZvt',
  'danceability': 0.608,
  'energy': 0.772,
  'valence': 0.339,
  'popularity': 43},
 {'track_name': 'Lines of the Broken',
  'artist': 'DROELOE, San Holo, CUT_',
  'album': 'Lines of the Broken',
  'track_uri': 'spotify:track:38q117S1yZJorvr6hvMhkT',
  'danceability': 0.591,
  'energy': 0.569,
  'valence': 0.304,
  'popularity': 43},
 {'track_name': 'Dead Man Walking',
  'artist': 'Grant, ellis',
  'album': 'Dead Man Walking',
  'track_uri': 'spotify:track:4ZPwjq0CdxbWFNycxnSUJc',
  'danceability': 0.695,
  'energy': 0.689,
  'valence': 0.496,
  'popularity': 52},
 {'track_name': 'Are We Still Young',
  'artist': 'Grant, Juneau',
  'album': 'Are We Still Young',
  'track_uri': 'spotify:track:7zPAsqqz9M5qcpG42YUiug',
  'danceability': 0.619,
  'energy': 0.714,
  'valence': 0.432,
  'popularity': 47},
 {'track_name': 'Color',
  'artist': 'Grant, Juneau',
  'album': 'Color',
  'track_uri': 'spotify:track:5gneV1qwaIndUU4aZ3uhXP',
  'danceability': 0.659,
  'energy': 0.672,
  'valence': 0.289,
  'popularity': 47},
 {'track_name': 'The Edge',
  'artist': 'Grant, Nevve',
  'album': 'The Edge',
  'track_uri': 'spotify:track:2P8MOT07PrPiTjqNPKWVsp',
  'danceability': 0.507,
  'energy': 0.864,
  'valence': 0.476,
  'popularity': 45},
 {'track_name': 'Castaway',
  'artist': 'Grant, Juneau',
  'album': 'Castaway',
  'track_uri': 'spotify:track:63psBh1jACfpWZtpZQZbVM',
  'danceability': 0.614,
  'energy': 0.655,
  'valence': 0.641,
  'popularity': 44},
 {'track_name': 'Wishes',
  'artist': 'Grant, McCall',
  'album': 'Wishes',
  'track_uri': 'spotify:track:4H1FdAyWZBNzwcHFQYeGy6',
  'danceability': 0.244,
  'energy': 0.721,
  'valence': 0.114,
  'popularity': 43},
 {'track_name': 'Weapon',
  'artist': 'Grant, BAUM',
  'album': 'Weapon',
  'track_uri': 'spotify:track:0jdi6xVBhk96OEoO53yORN',
  'danceability': 0.609,
  'energy': 0.885,
  'valence': 0.542,
  'popularity': 43},
 {'track_name': 'Move On',
  'artist': 'Grant, Emily Vaughn',
  'album': 'Move On',
  'track_uri': 'spotify:track:5jnoK2o5jY46qhPR30RepX',
  'danceability': 0.492,
  'energy': 0.812,
  'valence': 0.607,
  'popularity': 43},
 {'track_name': 'High Enough',
  'artist': 'Grant, Will Jay',
  'album': 'High Enough',
  'track_uri': 'spotify:track:6qv0ptzHveUZEy4cwxoRg3',
  'danceability': 0.656,
  'energy': 0.864,
  'valence': 0.828,
  'popularity': 41},
 {'track_name': 'Lush',
  'artist': 'Grant',
  'album': 'Lush',
  'track_uri': 'spotify:track:0ZLBYoLxyONV8gOhlYXL6q',
  'danceability': 0.44,
  'energy': 0.968,
  'valence': 0.202,
  'popularity': 39}]


## Save the top tracks info to a dataframe for analysis

In [26]:
df_top_tracks = pd.DataFrame(track_info_list)

In [27]:
df_top_tracks.head()

,track_name,artist,album,track_uri,danceability,energy,valence,popularity
0,Shelter,"Porter Robinson, Madeon",Shelter,spotify:track:2ewEh7LuvToYyGHq7yT8N1,0.477,0.796,0.2700,61
1,Cheerleader,Porter Robinson,SMILE! :D,spotify:track:5iyuwVaMliMdloOzSBxohv,0.464,0.701,0.2770,58
2,Everything Goes On,"Porter Robinson, League of Legends",Everything Goes On,spotify:track:3WBRfkOozHEsG0hbrBzwlm,0.550,0.648,0.3230,60
3,Goodbye To A World,Porter Robinson,Worlds,spotify:track:786ymAh5BmHoIpvjyrvjXk,0.444,0.350,0.0973,58
4,Knock Yourself Out XD,Porter Robinson,SMILE! :D,spotify:track:6yfY7OdAz4VEOjPUOP3yzN,0.554,0.741,0.3320,56

In [28]:
'''
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df_top_tracks)
'''

'\nfrom google.colab import sheets\nsheet = sheets.InteractiveSheet(df=df_top_tracks)\n'

# Filter tracks based on audio features
Select the audio features and thresholds based on your preferences.

In [29]:
df_playlist_tracks = df_top_tracks.query('danceability < 0.7 and valence < 0.7')
df_playlist_tracks

,track_name,artist,album,track_uri,danceability,energy,valence,popularity
0,Shelter,"Porter Robinson, Madeon",Shelter,spotify:track:2ewEh7LuvToYyGHq7yT8N1,0.477,0.796,0.2700,61
1,Cheerleader,Porter Robinson,SMILE! :D,spotify:track:5iyuwVaMliMdloOzSBxohv,0.464,0.701,0.2770,58
2,Everything Goes On,"Porter Robinson, League of Legends",Everything Goes On,spotify:track:3WBRfkOozHEsG0hbrBzwlm,0.550,0.648,0.3230,60
3,Goodbye To A World,Porter Robinson,Worlds,spotify:track:786ymAh5BmHoIpvjyrvjXk,0.444,0.350,0.0973,58
4,Knock Yourself Out XD,Porter Robinson,SMILE! :D,spotify:track:6yfY7OdAz4VEOjPUOP3yzN,0.554,0.741,0.3320,56
5,Is There Really No Happiness?,Porter Robinson,SMILE! :D,spotify:track:3eE6IderHf7lnqOorqiNVK,0.608,0.838,0.6310,57
6,Russian Roulette,Porter Robinson,SMILE! :D,spotify:track:3RdUgst4llmyJkVtNaqHGv,0.550,0.780,0.2200,55
7,Sad Machine,Porter Robinson,Worlds,spotify:track:1JY6B9ILvmRla2IKKRZvnH,0.470,0.706,0.3270,55
8,Look at the Sky,Porter Robinson,Nurture,spotify:track:5lXNcc8QeM9KpAWNHAL0iS,0.568,0.564,0.3850,55
10,Shelter,"Porter Robinson, Madeon",Shelter,spotify:track:2ewEh7LuvToYyGHq7yT8N1,0.477,0.796,0.2700,61
11,Love You Back,Madeon,Love You Back,spotify:track:5wM6LOw2U6XeIFHfsgI6wU,0.511,0.718,0.2740,50
12,You're On (feat. Kyan),"Madeon, Kyan",Adventure (Deluxe),spotify:track:4PTPZeJlK1rYlYr6bf11hk,0.490,0.914,0.2410,47
13,Finale (feat. Nicholas Petricca),"Madeon, Nicholas Petricca",Adventure (Deluxe),spotify:track:4ATmY1hv93ehw77LrIdbEh,0.417,0.859,0.1790,43
14,Believe It,"Louis The Child, Madeon",The Sun Comes Up,spotify:track:1IzM5hoLr4bUq57FOrWXQ2,0.669,0.926,0.5080,46
15,All My Friends,Madeon,Good Faith,spotify:track:3ArdPRbscsYB2uI70AzpuG,0.668,0.764,0.6850,46
16,The City,Madeon,Adventure (Deluxe),spotify:track:36HA2woC1glnLa4vqWY3IC,0.520,0.825,0.2640,43
17,Pay No Mind (feat. Passion Pit),"Madeon, Passion Pit",Adventure (Deluxe),spotify:track:3rsq3qtqNBId48c0IVraTS,0.546,0.852,0.5580,44
20,Light,San Holo,Light,spotify:track:6jq6rcOikCZAmjliAgAmfT,0.570,0.763,0.4300,56
22,BRING BACK THE COLOR,"San Holo, AURORA",EXISTENTIAL DANCE MUSIC,spotify:track:2AHd1SRo5rAFvJOCEwLyTi,0.626,0.902,0.3950,47
23,feel again,"San Holo, Tchami",feel again,spotify:track:7LAFTet7LRO1ydBaqNRgr9,0.536,0.865,0.1630,49
24,lift me from the ground,"San Holo, Sofie Winterson",album1,spotify:track:7kZVirTc3V6d4YWtu6RaAu,0.572,0.690,0.3470,49
25,disappear,"San Holo, artemis orion, dobi",disappear,spotify:track:5BzLCBy61N1a6la0MVtueV,0.314,0.727,0.2320,48
26,We Will Meet Again,"San Holo, Jai Wolf",We Will Meet Again,spotify:track:6VpRQDOM7nQ6viuVUSXWGn,0.401,0.786,0.2640,45
27,what is life?,"San Holo, Bipolar Sunshine",what is life?,spotify:track:4nBTt4n122lScgQwHzKVCV,0.458,0.686,0.3620,42
28,GLOW (feat. Au/Ra),"San Holo, Au/Ra",GLOW (feat. Au/Ra),spotify:track:3lqfTqap6aFMlYGEOyDZvt,0.608,0.772,0.3390,43
29,Lines of the Broken,"DROELOE, San Holo, CUT_",Lines of the Broken,spotify:track:38q117S1yZJorvr6hvMhkT,0.591,0.569,0.3040,43
30,Dead Man Walking,"Grant, ellis",Dead Man Walking,spotify:track:4ZPwjq0CdxbWFNycxnSUJc,0.695,0.689,0.4960,52
31,Are We Still Young,"Grant, Juneau",Are We Still Young,spotify:track:7zPAsqqz9M5qcpG42YUiug,0.619,0.714,0.4320,47
32,Color,"Grant, Juneau",Color,spotify:track:5gneV1qwaIndUU4aZ3uhXP,0.659,0.672,0.2890,47
33,The Edge,"Grant, Nevve",The Edge,spotify:track:2P8MOT07PrPiTjqNPKWVsp,0.507,0.864,0.4760,45
34,Castaway,"Grant, Juneau",Castaway,spotify:track:63psBh1jACfpWZtpZQZbVM,0.614,0.655,0.6410,44
35,Wishes,"Grant, McCall",Wishes,spotify:track:4H1FdAyWZBNzwcHFQYeGy6,0.244,0.721,0.1140,43
36,Weapon,"Grant, BAUM",Weapon,spotify:track:0jdi6xVBhk96OEoO53yORN,0.609,0.885,0.5420,43
37,Move On,"Grant, Emily Vaughn",Move On,spotify:track:5jnoK2o5jY46qhPR30RepX,0.492,0.812,0.6070,43
39,Lush,Grant,Lush,spotify:track:0ZLBYoLxyONV8gOhlYXL6q,0.440,0.968,0.2020,39

In [30]:
len(df_playlist_tracks)

35

# Save the playlist tracks to a CSV file
You can analyze the file in Excel, a SQL database, visualization tool, or any other BI tool.

In [31]:
df_playlist_tracks.to_csv('playlist_tracks.csv', index=False)

## Get your Spotify user ID
The user ID is required to specify which Spotify account the new playlist will be created in.

Go to https://www.spotify.com/us/account/profile/

In [32]:
user_id = 'm4tthewcc'

## Create a playlist
https://developer.spotify.com/documentation/web-api/reference/create-playlist

In [33]:
playlist_url = f'https://api.spotify.com/v1/users/{user_id}/playlists'

playlist_name = f'{artist_name} Mixtape'
playlist_description = f'Python-generated playlist using artists related to {artist_name}'

data = json.dumps({
    'name': playlist_name,
    'description': playlist_description,
    'public': False
})

response = requests.post(playlist_url, headers = auth_headers, data = data)
playlist_response = response.json()

In [34]:
playlist_response

{'collaborative': False,
 'description': 'Python-generated playlist using artists related to Porter Robinson',
 'external_urls': {'spotify': 'https://open.spotify.com/playlist/2rFArqDobDNg2aSe18lnHS'},
 'followers': {'href': None, 'total': 0},
 'href': 'https://api.spotify.com/v1/playlists/2rFArqDobDNg2aSe18lnHS',
 'id': '2rFArqDobDNg2aSe18lnHS',
 'images': [],
 'primary_color': None,
 'name': 'Porter Robinson Mixtape',
 'type': 'playlist',
 'uri': 'spotify:playlist:2rFArqDobDNg2aSe18lnHS',
 'owner': {'href': 'https://api.spotify.com/v1/users/m4tthewcc',
  'id': 'm4tthewcc',
  'type': 'user',
  'uri': 'spotify:user:m4tthewcc',
  'display_name': None,
  'external_urls': {'spotify': 'https://open.spotify.com/user/m4tthewcc'}},
 'public': False,
 'snapshot_id': 'AAABk7FRHkm16q9TOEwYE7RmNvt/ZhMa',
 'tracks': {'limit': 100,
  'next': None,
  'offset': 0,
  'previous': None,
  'href': 'https://api.spotify.com/v1/playlists/2rFArqDobDNg2aSe18lnHS/tracks',
  'total': 0,
  'items': []}}

## Get the newly generated playlist ID

In [35]:
playlist_id = playlist_response['id']
playlist_id

'2rFArqDobDNg2aSe18lnHS'

## Get the track URIs (Uniform Resource Indicator) to then add to the playlist

In [36]:
df_playlist_tracks

,track_name,artist,album,track_uri,danceability,energy,valence,popularity
0,Shelter,"Porter Robinson, Madeon",Shelter,spotify:track:2ewEh7LuvToYyGHq7yT8N1,0.477,0.796,0.2700,61
1,Cheerleader,Porter Robinson,SMILE! :D,spotify:track:5iyuwVaMliMdloOzSBxohv,0.464,0.701,0.2770,58
2,Everything Goes On,"Porter Robinson, League of Legends",Everything Goes On,spotify:track:3WBRfkOozHEsG0hbrBzwlm,0.550,0.648,0.3230,60
3,Goodbye To A World,Porter Robinson,Worlds,spotify:track:786ymAh5BmHoIpvjyrvjXk,0.444,0.350,0.0973,58
4,Knock Yourself Out XD,Porter Robinson,SMILE! :D,spotify:track:6yfY7OdAz4VEOjPUOP3yzN,0.554,0.741,0.3320,56
5,Is There Really No Happiness?,Porter Robinson,SMILE! :D,spotify:track:3eE6IderHf7lnqOorqiNVK,0.608,0.838,0.6310,57
6,Russian Roulette,Porter Robinson,SMILE! :D,spotify:track:3RdUgst4llmyJkVtNaqHGv,0.550,0.780,0.2200,55
7,Sad Machine,Porter Robinson,Worlds,spotify:track:1JY6B9ILvmRla2IKKRZvnH,0.470,0.706,0.3270,55
8,Look at the Sky,Porter Robinson,Nurture,spotify:track:5lXNcc8QeM9KpAWNHAL0iS,0.568,0.564,0.3850,55
10,Shelter,"Porter Robinson, Madeon",Shelter,spotify:track:2ewEh7LuvToYyGHq7yT8N1,0.477,0.796,0.2700,61
11,Love You Back,Madeon,Love You Back,spotify:track:5wM6LOw2U6XeIFHfsgI6wU,0.511,0.718,0.2740,50
12,You're On (feat. Kyan),"Madeon, Kyan",Adventure (Deluxe),spotify:track:4PTPZeJlK1rYlYr6bf11hk,0.490,0.914,0.2410,47
13,Finale (feat. Nicholas Petricca),"Madeon, Nicholas Petricca",Adventure (Deluxe),spotify:track:4ATmY1hv93ehw77LrIdbEh,0.417,0.859,0.1790,43
14,Believe It,"Louis The Child, Madeon",The Sun Comes Up,spotify:track:1IzM5hoLr4bUq57FOrWXQ2,0.669,0.926,0.5080,46
15,All My Friends,Madeon,Good Faith,spotify:track:3ArdPRbscsYB2uI70AzpuG,0.668,0.764,0.6850,46
16,The City,Madeon,Adventure (Deluxe),spotify:track:36HA2woC1glnLa4vqWY3IC,0.520,0.825,0.2640,43
17,Pay No Mind (feat. Passion Pit),"Madeon, Passion Pit",Adventure (Deluxe),spotify:track:3rsq3qtqNBId48c0IVraTS,0.546,0.852,0.5580,44
20,Light,San Holo,Light,spotify:track:6jq6rcOikCZAmjliAgAmfT,0.570,0.763,0.4300,56
22,BRING BACK THE COLOR,"San Holo, AURORA",EXISTENTIAL DANCE MUSIC,spotify:track:2AHd1SRo5rAFvJOCEwLyTi,0.626,0.902,0.3950,47
23,feel again,"San Holo, Tchami",feel again,spotify:track:7LAFTet7LRO1ydBaqNRgr9,0.536,0.865,0.1630,49
24,lift me from the ground,"San Holo, Sofie Winterson",album1,spotify:track:7kZVirTc3V6d4YWtu6RaAu,0.572,0.690,0.3470,49
25,disappear,"San Holo, artemis orion, dobi",disappear,spotify:track:5BzLCBy61N1a6la0MVtueV,0.314,0.727,0.2320,48
26,We Will Meet Again,"San Holo, Jai Wolf",We Will Meet Again,spotify:track:6VpRQDOM7nQ6viuVUSXWGn,0.401,0.786,0.2640,45
27,what is life?,"San Holo, Bipolar Sunshine",what is life?,spotify:track:4nBTt4n122lScgQwHzKVCV,0.458,0.686,0.3620,42
28,GLOW (feat. Au/Ra),"San Holo, Au/Ra",GLOW (feat. Au/Ra),spotify:track:3lqfTqap6aFMlYGEOyDZvt,0.608,0.772,0.3390,43
29,Lines of the Broken,"DROELOE, San Holo, CUT_",Lines of the Broken,spotify:track:38q117S1yZJorvr6hvMhkT,0.591,0.569,0.3040,43
30,Dead Man Walking,"Grant, ellis",Dead Man Walking,spotify:track:4ZPwjq0CdxbWFNycxnSUJc,0.695,0.689,0.4960,52
31,Are We Still Young,"Grant, Juneau",Are We Still Young,spotify:track:7zPAsqqz9M5qcpG42YUiug,0.619,0.714,0.4320,47
32,Color,"Grant, Juneau",Color,spotify:track:5gneV1qwaIndUU4aZ3uhXP,0.659,0.672,0.2890,47
33,The Edge,"Grant, Nevve",The Edge,spotify:track:2P8MOT07PrPiTjqNPKWVsp,0.507,0.864,0.4760,45
34,Castaway,"Grant, Juneau",Castaway,spotify:track:63psBh1jACfpWZtpZQZbVM,0.614,0.655,0.6410,44
35,Wishes,"Grant, McCall",Wishes,spotify:track:4H1FdAyWZBNzwcHFQYeGy6,0.244,0.721,0.1140,43
36,Weapon,"Grant, BAUM",Weapon,spotify:track:0jdi6xVBhk96OEoO53yORN,0.609,0.885,0.5420,43
37,Move On,"Grant, Emily Vaughn",Move On,spotify:track:5jnoK2o5jY46qhPR30RepX,0.492,0.812,0.6070,43
39,Lush,Grant,Lush,spotify:track:0ZLBYoLxyONV8gOhlYXL6q,0.440,0.968,0.2020,39

In [37]:
track_uris = []

for index, row in df_playlist_tracks.iterrows():
    track_uri = row['track_uri']
    print(f'track_uri: {track_uri}')
    track_uris.append(track_uri)

track_uri: spotify:track:2ewEh7LuvToYyGHq7yT8N1
track_uri: spotify:track:5iyuwVaMliMdloOzSBxohv
track_uri: spotify:track:3WBRfkOozHEsG0hbrBzwlm
track_uri: spotify:track:786ymAh5BmHoIpvjyrvjXk
track_uri: spotify:track:6yfY7OdAz4VEOjPUOP3yzN
track_uri: spotify:track:3eE6IderHf7lnqOorqiNVK
track_uri: spotify:track:3RdUgst4llmyJkVtNaqHGv
track_uri: spotify:track:1JY6B9ILvmRla2IKKRZvnH
track_uri: spotify:track:5lXNcc8QeM9KpAWNHAL0iS
track_uri: spotify:track:2ewEh7LuvToYyGHq7yT8N1
track_uri: spotify:track:5wM6LOw2U6XeIFHfsgI6wU
track_uri: spotify:track:4PTPZeJlK1rYlYr6bf11hk
track_uri: spotify:track:4ATmY1hv93ehw77LrIdbEh
track_uri: spotify:track:1IzM5hoLr4bUq57FOrWXQ2
track_uri: spotify:track:3ArdPRbscsYB2uI70AzpuG
track_uri: spotify:track:36HA2woC1glnLa4vqWY3IC
track_uri: spotify:track:3rsq3qtqNBId48c0IVraTS
track_uri: spotify:track:6jq6rcOikCZAmjliAgAmfT
track_uri: spotify:track:2AHd1SRo5rAFvJOCEwLyTi
track_uri: spotify:track:7LAFTet7LRO1ydBaqNRgr9
track_uri: spotify:track:7kZVirTc3V6d4YWtu6RaAu
track_uri: spotify:track:5BzLCBy61N1a6la0MVtueV
track_uri: spotify:track:6VpRQDOM7nQ6viuVUSXWGn
track_uri: spotify:track:4nBTt4n122lScgQwHzKVCV
track_uri: spotify:track:3lqfTqap6aFMlYGEOyDZvt
track_uri: spotify:track:38q117S1yZJorvr6hvMhkT
track_uri: spotify:track:4ZPwjq0CdxbWFNycxnSUJc
track_uri: spotify:track:7zPAsqqz9M5qcpG42YUiug
track_uri: spotify:track:5gneV1qwaIndUU4aZ3uhXP
track_uri: spotify:track:2P8MOT07PrPiTjqNPKWVsp
track_uri: spotify:track:63psBh1jACfpWZtpZQZbVM
track_uri: spotify:track:4H1FdAyWZBNzwcHFQYeGy6
track_uri: spotify:track:0jdi6xVBhk96OEoO53yORN
track_uri: spotify:track:5jnoK2o5jY46qhPR30RepX
track_uri: spotify:track:0ZLBYoLxyONV8gOhlYXL6q

In [38]:
track_uris

['spotify:track:2ewEh7LuvToYyGHq7yT8N1',
 'spotify:track:5iyuwVaMliMdloOzSBxohv',
 'spotify:track:3WBRfkOozHEsG0hbrBzwlm',
 'spotify:track:786ymAh5BmHoIpvjyrvjXk',
 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN',
 'spotify:track:3eE6IderHf7lnqOorqiNVK',
 'spotify:track:3RdUgst4llmyJkVtNaqHGv',
 'spotify:track:1JY6B9ILvmRla2IKKRZvnH',
 'spotify:track:5lXNcc8QeM9KpAWNHAL0iS',
 'spotify:track:2ewEh7LuvToYyGHq7yT8N1',
 'spotify:track:5wM6LOw2U6XeIFHfsgI6wU',
 'spotify:track:4PTPZeJlK1rYlYr6bf11hk',
 'spotify:track:4ATmY1hv93ehw77LrIdbEh',
 'spotify:track:1IzM5hoLr4bUq57FOrWXQ2',
 'spotify:track:3ArdPRbscsYB2uI70AzpuG',
 'spotify:track:36HA2woC1glnLa4vqWY3IC',
 'spotify:track:3rsq3qtqNBId48c0IVraTS',
 'spotify:track:6jq6rcOikCZAmjliAgAmfT',
 'spotify:track:2AHd1SRo5rAFvJOCEwLyTi',
 'spotify:track:7LAFTet7LRO1ydBaqNRgr9',
 'spotify:track:7kZVirTc3V6d4YWtu6RaAu',
 'spotify:track:5BzLCBy61N1a6la0MVtueV',
 'spotify:track:6VpRQDOM7nQ6viuVUSXWGn',
 'spotify:track:4nBTt4n122lScgQwHzKVCV',
 'spotify:track:3lqfTqap6aFMlYGEOyDZvt',
 'spotify:track:38q117S1yZJorvr6hvMhkT',
 'spotify:track:4ZPwjq0CdxbWFNycxnSUJc',
 'spotify:track:7zPAsqqz9M5qcpG42YUiug',
 'spotify:track:5gneV1qwaIndUU4aZ3uhXP',
 'spotify:track:2P8MOT07PrPiTjqNPKWVsp',
 'spotify:track:63psBh1jACfpWZtpZQZbVM',
 'spotify:track:4H1FdAyWZBNzwcHFQYeGy6',
 'spotify:track:0jdi6xVBhk96OEoO53yORN',
 'spotify:track:5jnoK2o5jY46qhPR30RepX',
 'spotify:track:0ZLBYoLxyONV8gOhlYXL6q']

In [39]:
track_uris = df_playlist_tracks['track_uri'].tolist()

In [40]:
track_uris

['spotify:track:2ewEh7LuvToYyGHq7yT8N1',
 'spotify:track:5iyuwVaMliMdloOzSBxohv',
 'spotify:track:3WBRfkOozHEsG0hbrBzwlm',
 'spotify:track:786ymAh5BmHoIpvjyrvjXk',
 'spotify:track:6yfY7OdAz4VEOjPUOP3yzN',
 'spotify:track:3eE6IderHf7lnqOorqiNVK',
 'spotify:track:3RdUgst4llmyJkVtNaqHGv',
 'spotify:track:1JY6B9ILvmRla2IKKRZvnH',
 'spotify:track:5lXNcc8QeM9KpAWNHAL0iS',
 'spotify:track:2ewEh7LuvToYyGHq7yT8N1',
 'spotify:track:5wM6LOw2U6XeIFHfsgI6wU',
 'spotify:track:4PTPZeJlK1rYlYr6bf11hk',
 'spotify:track:4ATmY1hv93ehw77LrIdbEh',
 'spotify:track:1IzM5hoLr4bUq57FOrWXQ2',
 'spotify:track:3ArdPRbscsYB2uI70AzpuG',
 'spotify:track:36HA2woC1glnLa4vqWY3IC',
 'spotify:track:3rsq3qtqNBId48c0IVraTS',
 'spotify:track:6jq6rcOikCZAmjliAgAmfT',
 'spotify:track:2AHd1SRo5rAFvJOCEwLyTi',
 'spotify:track:7LAFTet7LRO1ydBaqNRgr9',
 'spotify:track:7kZVirTc3V6d4YWtu6RaAu',
 'spotify:track:5BzLCBy61N1a6la0MVtueV',
 'spotify:track:6VpRQDOM7nQ6viuVUSXWGn',
 'spotify:track:4nBTt4n122lScgQwHzKVCV',
 'spotify:track:3lqfTqap6aFMlYGEOyDZvt',
 'spotify:track:38q117S1yZJorvr6hvMhkT',
 'spotify:track:4ZPwjq0CdxbWFNycxnSUJc',
 'spotify:track:7zPAsqqz9M5qcpG42YUiug',
 'spotify:track:5gneV1qwaIndUU4aZ3uhXP',
 'spotify:track:2P8MOT07PrPiTjqNPKWVsp',
 'spotify:track:63psBh1jACfpWZtpZQZbVM',
 'spotify:track:4H1FdAyWZBNzwcHFQYeGy6',
 'spotify:track:0jdi6xVBhk96OEoO53yORN',
 'spotify:track:5jnoK2o5jY46qhPR30RepX',
 'spotify:track:0ZLBYoLxyONV8gOhlYXL6q']

## Add tracks to the playlist
https://developer.spotify.com/documentation/web-api/reference/add-tracks-to-playlist

In [41]:
playlist_tracks_url = f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks'

data = json.dumps({
    'uris': track_uris
})

response = requests.post(playlist_tracks_url, headers=auth_headers, data=data)
playlist_tracks_response = response.json()

In [42]:
playlist_tracks_response

{'snapshot_id': 'AAAAAuvKEg9uhCuYsPP3c1DGMaOX6PPC'}

## Create another playlist! 🎶
Update the artist_name value.

If your access token is still valid, you can "Run cell and below" starting from the "Search for an artist and get their artist ID" cell.